---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hass-passwords
  namespace: hass
spec:
  encryptedData:
    hass-passwords.json: AgCHIWWXRuW6L5+A6ANXLQpK+WlVBXVm2EWUr0oxSvYx8wCOHhxEgHGeK48nsxwlI4DNIPtVJINqFBOmHjiRalV1xdJSa4lD0ZH19ktc4dfFCjS33f02DSmhVbvdh6+RzyZ4VZ2rSyHD55tnu4KUlb+YbRuKyO9xQnCvSi03eEPnjarRQBfiEiEdIvsNAjdKDdKr229oZqnKYBcss92j4IUxX8DsqnoXxfeJEztohG6lsRW9AApbHoq88ZYIIFGgWWqR9EKbxjy1jGN2OPcFdoc5BbVMRhurOWvy5QQW3j0dadUc3G5sJY3HBoZVXmE416LzFqVrLUUKxpGthLo0dmLnLfqcstszZIyYCVzlfB5wVAYraVydJ9bouk35qx9rKDS96qwDjj1CCottaPVGK/Um56BIjDe+7c5PcObLWskGxt4lGmSbALIxQh5wKgojNuhnZbKogp1CrAWEoi3pwJwIGe7HfWPyE4byFwhsTgJVSCOCJPUF7SG924TpoblcFyz8hg+as/uxwtj7g7L30EByDHLuN6Ndx0RpuydhVrAgf1V9YkqW5BnvvqrGvAtgacWEEFvWuFRLl2K+gzbR1Kq/xLFqdxbIHmxA1shLxThux5EXR8T303KXVZaMfmF4ojnKMkJLgb4XA/TzwZwf98x8Y7EbTqZwsOEZC5KBJQRTLnzaSNygpoyzPE+c24T4Aor3x5mLJUFkiLHGDMRNFyCHDnTqmQxZtUjj8XiBFv/rssoBh4SAu3qMQForQ+9tGetGss7moF39vr5zojDwxq4T7Oqbr/6bwNJQPwK6yB3/KbdPdiNKchI1RMbkr2OFR0JL49vvtTKHGC4L0evo6pp/w0+RMPJ8sBHJdnyA0EhIr5vSiaFm6c+rBuemtjl5YEoVwre/nh56gH3AFAh65H5uMBjLn92Rhq/F5UkXEIe/uoj5SSN2eWZI+dtI5UaAzGkmcABoAbu1vXuCWhflo+9d25vKGjai9X2Yridt5Ie+c7edp6YT7TYzLaref589W2vGdqIMLSjl4fAVp4zkeJVZrJxGho8pLC3WiQcnYXw3oS/AMfjVrQ4V553vchpjSRQTKtdtfZVaBQQuHVhxz21fjwBpIN8CtfI/JwVllyr3totrvmMGwBaQ/TuGnHgPgU81IeI8LYlQKEkUhaXCqhI91gennowjKYR1CuzU7T3KOBe5jhkzkFh7BHKVHaqDZOX/D666g3zKhdgvGohGlyvWg5pbMUkuj3dl8GmUBChQKjczfdYWdxTeK9QnnRsH8EKE8KD6QkhJI6GTLyna0aLSI9NEsft3HQDggM13OpuwHWsW1Q6rDBmq69aQq3MlQhoq7UyAx6xF+UW5wkUpdAYUcTpoztjFERhXNRXmxOHEFGZ5l2oLMcMi+5lmP1ydrNQIEKOU/llS6LAr0GAyhxDSiCHHy9NE3zdYa8NGs4SHEKlLPBE=
  template:
    metadata:
      creationTimestamp: null
      name: hass-passwords
      namespace: hass
