---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hass-secrets
  namespace: hass
spec:
  encryptedData:
    secret.yaml: AgA6pvwOhvHHsMVSf7fzLLKkItGaOXMoro9NckxtsBH9l5NbICfiDvvGNoS5C7SLkvxCwizvQkTxdtP+sIuUyZB1Wf1HGcDmWm0kQitH7G1Uw/T2w/aU94aBApKgrYcX4pJTnfur3JXxDKFr4B6SZqF5OPR6rUib8l8jULeYm3OW16oV7afgs3lvWAMEMsfX38XO9jDneU0Xh0tAIm336BW6sRVHpqCQT275pTEQxmWnww94xuf+wCI0bbkn2v76VFnNpOeGPAlr8QDOs7gT1rUAvH0xEQg6GdArwZctA9Y1C/AajHwnzgOCZtBKd9A8HHyPHHHsjRhvb+O1LTVN/s39TvGZ88x5fy9295a5gn3UDBg2qmdXrDwEyl87PuGEXA4K+SQGlr0I1xFJBnANjgLbnUEyh13cU/Lm5htGbhgEM9dMsEheUFZZWef6WdCgNuzxD9i4VeuxdOR73QXjJciAV2q6ZVq5hO3tLucvO8A4ho+h9HdQLm7QU2yZtRWy5eNi/ydcJzwXigcEf2F5RudvYNALRANOURIH24D9cR/kkFBZeXtwpVJBuwUpNFe1n9T5qI4WSkfW5JhRWq5OrS8+nF6aqQtQBJA2kDhw+xJWSq4NJEnucNlTspYKjefP03CoDYsGyQZwxc85rdOVvZO9l//P+Gx7+3znzf+8yHkyxQg+nnn2hLsduFYXC30aHYRAbAP+OC04TT1ju+vbfYU1Mdpu3UKFHg+sAE8MELha1QSThGqfo0rrMGck+wZVS6iDCAgw1HCEro04vIIluEPhLHkE1VmolW5a0EYRj2HHHbcfBgB4EKcabXr94Kyo/u4pRSfkt3jWE4ZvH+wenjcMrrutOqiNbM9WyIQzMaN4IwxfN4eBGYlqWokGz1JAfbRVXLp3qnnseF+Kybn6kuMA06w10tYsDT7O+47YPnywRJbf9jZnOpn1
  template:
    metadata:
      name: hass-secrets
      namespace: hass
