---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mosquitto-passwordfile
  namespace: mosquitto
spec:
  encryptedData:
    passwordfile: AgADCKxAoIh7ZyDLoS9bkGqsJlmwor0Ua0QlwxAE9TpeL5cFw8A235zXeMWdiYTiCOaMh9UqCVqvVVPENv6A5O4Frd9ckya+A+6KK+LwCyuDC2NFcneHPU31wRvmgSeVLaz3zUWkN4zHkhZx9kmfj3eYFL7f75jPkU8pUeL/VChRe4tkVEhPbiw8vgzWZJ1DRweFnBJ2UW4+6vzNUuDNXoL7O0TgOUKfyscAGy9zyp7xloQtZyks7Fe8qczpsKm8QYUCrTTzg4gzyimlh9tsA5JOwFU/dKDz32zcxmLQqqKWdR4lqqg+UkiMJFp31w9hx0b2l+lJJ6IA516Xvs3NCg/Zo51mPD4lmstKnHyznOpp7m+IN1UfvG657U+cgwqddgWukppIEpHPUPqZS/XQzHERhnm3ZSSSDonHvTf1lAGhc4f06p6QpdNERU1VVBmXEQQ453LZCLax1bgPLBl0KiF4Q5xrwkTCm4tvxKDcJV3Ya0hoYxssseafnVR/H0nRQkMGx7myr11Jwz3Mz9BTavT6W8O5DXglLQnf8c+XvI/46GXf5x7VBjAhI1J4+O8eP+1pfkeUGi4sb34PetEH763KYgnEDAQWhWzhk+h8VZvidL2llKWpt9l8ee2lLxPEo7V1x/rGLs483F5ruDzLf5LZcEj8oQUNUslPEjGYs9un1CKWQAIw3+TI7w+Iv9swq3k/aBfkF15AgJROLLfCAxcWUFTGsshhYnEodsBn8VSdyADPABoMXMBVItuJ0+v8dHt7FoOviEAtCKljjWexhrezvPbQeqWiNZZPq+FtryA/PxW4LZEORFdEjsjFUU9h6oZYLsLZ0BEHsVqo12Qxepqd9AoOi9Gr
  template:
    metadata:
      name: mosquitto-passwordfile
      namespace: mosquitto
