---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mosquitto-passwordfile
  namespace: mosquitto
spec:
  encryptedData:
    passwordfile: AgBO05WJqzi5rz2UGsGD/NILKndPGbiA8wGGqUKWL6CtBGgNx5m7T0/UgWaPhwQ3fzqW2s1FRjDlf2baqbUf2hqsYfIDasdq+Jze4y06e7a3TxG/LrOHVE8qBV45JB9KawIOaEUiD2eHtv3un3wFgxHTyvoeecIx7Ynd/29Zv73CQSv+NaQeUDwL3jq17geg51CBiU4r9/kBTiX2Xl81PeLO6iCPs80WlPYK2VLX2hNR5/F3kg/nc19DgTa9o95ddvBjdfWv32MNCl693CvQryAXBnA7+xFfeQCFPB4QVtMUe8KzfKNzDrhqdk2OJJlcgepT2Tz0FOIr6xyyfNCEn//xYtAcv6LuhjJhbRVy8t7Rb9/5y26pwqTgkYOD5Tx3H/H1MX/8H8rJmNq7CbpGwJEhfjOBJ37PIfhp3ys9Ga4rNVeXIX6byKbgoNoliTcG+zhffN+grwsjirkZ37ScMN2qdsJcTeIUT2r6T1raOf3Y4qfR0YVYP01+RWJLIBkIjkLSc7OJPiiSccZretheGvgnGauNrhL+TdLnSlZHGduUL2S2j3rRZBBzmbBG3EJZKnQwbjzoO3o0R8zUy74B9zQUlURnUe29cHBQ9bGoy+PGtufTVRqeZzUqyB/hHxSbcc7lNEASG/mFQZxu/bTuFw8yNEuosYd+WLy3pxN2DZqaZa7s9c66T/bt7gkgunIRkbRXYPN6l+GxYr8D6miGot4LiZR82Q2KGlfv9KSWNJ5/tL3sJ2ECG+FSDY2YLPAawYv+qkF3PkqW5NTYrK8SKZnUCp76c5DGGcYXNJ0q6BWlpIP+/prg72t6UBaRGzAarD/wxmkeWmG+rIi+EjnNcx5q6qlWZ1RF
  template:
    metadata:
      name: mosquitto-passwordfile
      namespace: mosquitto
