---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-passwordfile
  namespace: mosquitto
spec:
  encryptedData:
    passwordfile: AgA2WtVABR9oho8wz2DgutrwlU05eNjwvjRIHANzMeb8efcGfZGZPhvSVgdxchCVolf+qmPoHtvs2mP52P2Jt3VKYG/HThPhQ1+idCdfIxFeEaHCGB1yf3GxcGlqibnxPD094/dqipUe9UG0oIM2CfcMlnKzneVVdYl6ivyeW/51tjxXHO2iVPSdlrx+KIFKllLF1/v8XaGL4T3K6MrJKBdifXbmf6sYVoJgPvkqa9iEi4vJKVVdF5q8u73A/z7sPQsS/1FLl7lGD1SYJM5g8nHwYuRJu319ZFKAGMv+65qBWIbuX3GAEqCD8kb4bBvH//XRycgzyUVUd7BUNlSE/YC9nObJ6gIlumgCl8U1G8uV+J3+l0nXKOqlK4HnSdpjtOT39InYohk7MW8tpbZG2y/wfMtL231t+4LM99vU6wYf92y/Y7NNPfpf59bM1QBRSarXGK/AoWyCjNX5uwoLWbons9X0vUeZqvLOeQQiC4HIGdfofcQ1UQMak36WGk2JrbCM9kiYYI1C2+elBjqfA0lk5mNqbt4EHYNgLQV3Ctp0g6vIgyhf7okzXPn0IF3RAemlv1aHcaMXrviT+lCUa4cOVjulUJfuNlrxL0COF+q/IfpsacIx7sylQo4xBqmhxlJsvlX2uzOs8DPYd5CRcTRicQFUymUD1btdyXXOZ/NIm2MIcQSf2gfwySwgeOZbTrtsOaWRJ+UVF4fCaX9DE+iRWv233g3iilxlAvWZW76UHXAZx+h41ofxeX8viDgcC8ssDJWIHlKUzE1anPfqj6O5eHI7S/N1/ly6n/e4/It70MnQ3gjqCmdrTU3gVn4+BXPot7B67nNK1GozsRzUrIjylBaJ1MtH
  template:
    metadata:
      creationTimestamp: null
      name: mosquitto-passwordfile
      namespace: mosquitto
