---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  encryptedData:
    secret.yaml: AgAQcBkYIjNUnooPotn4yM1wbJ41veiUmS/cii2GVr+C9vEQd5aFs+YhclQvNNPKC9PsfVuYQZdmjCPHhaxci/O1jHGpsk74g/lQmD/AizvtEAMMKk/8gFOXW+pTU97e+RUkNFgkeW684W3/sz62RFJCrir4+3/m/w9fMkN9GSIEpcNqiwGNnkfBgFatahruAd1PZRM3AqyBaUDqGOHNQhBTHzN2B4yp1C50hkTCoudmE0Wrg9lkF7hT8wditp2sUUsgJgX7Wxz5WNX748TuQtqxuDv56hBi1K2WXbOiYtiv9muf51MmZxa/eqpNE5cF+wRHV8NRvtXAz7ij1QofCyHvBl1mLM6ty385mipjIEi+JUoaUFJfG8FCng9whBKbZNIKlOLzlYIESPyUIizP/0ajpLFIleKjbwOUiKhlKTsQX7MQaHn+SNUUIGWEJtePkyT/MTY+g6o6CwecVnTXiFSK7GQUS9ZlaUHJhJBSKUlwDAoXpb0e8pUFL6KbQFhIttgoPX4NpkSqS136RqWp43vsyR1Ulb7uYwgV0g83XNkWFmeMqeGUMLIxGctDTMOPV0DIvWxu93wjsZXwPBIjhtrodTM6KmWTIrYEGmwjhERFNQvFbi81vWaZW04yns/mfD/BZfA/HRF4dijIk67V4OA+S+W3SbB5IAqxXMNYz9LJf2s9QnFHtNsLZ7/tW1KDYqWNVNtnRZsQI6ka9bMOd5rag01WfEYmlDMcXHFXph6+6qD3wuucOYU/0YPgI0pwq2YA6gdFmQtFwOia9dwz8LregrfRxGJF/H43VB9HZTKfzmcVG9R32HPILaeGtK4=
  template:
    metadata:
      creationTimestamp: null
      name: zigbee2mqtt
      namespace: zigbee2mqtt
    type: Opaque
