---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  encryptedData:
    secret.yaml: AgB0DwR+n/JxZFJPP7jluSDmF6zMsgPKWeP5/LZl1+Vb4d+NEosqLlsFdlnZ2YsntfkHpqNOcQCdNfC6uHe+dnXp+8+td5sS5SwwgnqsTcwZnVWWzwUxaiwLcalXSPAm3tdlXEqyyIh0V8yK3U8hwgRB79zJuJB4vN0F0dt2KitC7gRI5oZG2wrvYEIPgxo1a3/2phpnWoTMjVjlRr3gUeRGvj61nFOXykFQbjkcJooZdXeZT71vm4mtqeW0ZhNCO9FLA8mvGDbC5d1UqxTyVfotV6law9ouC91tsrpy6Pxdv8NRKs1JdbIkuRb6kpO36ubyqglWI4K3o4khsEkdImfdH6DdNwEYotDkrFU6RP3zrAjGMwklLJG1cCojmEJrAj+8x/tQNUx1PSw3Kuvq5OcdxDuKgtti4Jm+qsS3kW6XfOgchq+ohW0WASz+HnqFAU2Nb3IL1CW2YTk/ZoOdI/k6YZh2weIadHCbFKKMklhUyT2+l0fif0htJ1th5/v6rEtu2jCkZ8rwUO/PrCL9GXYM/sRGSnqWS7UFchDsELW5unz8g8okH2L6yBtcNIqLPiiwPK82cpYt0MhHf8dbuZx0NYPtk80VQzybKS8HZUOybSWWPuXtBPTphaI//7cMCkKzkB4kB7S/7mzDcSGbf/LsweONQHcEWY+vZeGLtMwNrICd/XUF190bYvP47gPc4QD7uTDSU7Nv2W0RnmOw3zb2FoEeqk4FMqtzW2ykCb5RYt33Bz11LG2jcVrsTAVKgyjrh4KH68vKHlWTm6MsdCuHuEXLxrwmWCOpwVanneADHLst08pukwpTbXyF8zSUo2/HK5Eluz8ZftQwfKWAew==
  template:
    metadata:
      name: zigbee2mqtt
      namespace: zigbee2mqtt
