---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  encryptedData:
    secret.yaml: AgAquaQSwy1CrNHx7tiUO8Y1zgfof+vY1hgZPCOQOntxCWtkb9CyGsjl6KCvPJd/BIlcOxTnHfUBX7KFv+B6ZwvdHnf4XHkiFbSvTKNxn53IzlGPDRUYeBruJyQMy1RcxaORlzp7luiri5nQQ5NSILZfdOtav4hBKJyydVJjWbaBZ9ugHv0BTGxzHQ0m7ubUOVYhIiP5s/98YxN3f4bn+agC/hnE3YXxAYyF6nnlhFAl8aTp6E4mV5g/WzXYIUgBTU9dTMjyBgPyCeOPDZo5fcUAbRowUGKusMpQfw3hlIptgiSLP550IgukuuLOKxB00wWIZp2x7AFQ45pfC0A8aixR8+ZHEqqMo3KFvqfsa0w167z3WRsnABMBqN77xJFdAjsaEeY2xAklWkJOLEF9hTiA36P/D8LdYhMl7hoiIxiOLA3irmsaqdIkxffVdORP/AMeoICgSb5hex8cfCJIKI/HsAiiDbtZRqr/rfCV3cl42CLMXMYxavrIyPlYzdzAHOzKYAxe9a53Uu2gg3TUpaw+41TzNAYbIrZBXbQRoMGAluOtVWRBa/Q827oqfrTZlDwRGF2of3H2QUl8cwJISmZgbkKMl2pq0G1ed749VmyClFsf95KatnBzeYRyShNruZgipHIjy0jINdbK8As6jG/boPMlZYGVqlKOoEDAr1wE1oAd9O/MAgV+7d0rvPBq0PfiQRHxtU7Rfr/mf0QqP7MRdqRNkBRuDzfL7KdeHa/FtEYZAwFrOKR1xXZdaEOzry7fZVPQfIIS9E//8daoS4EyY1bEQ59HUU6EHHLrYdHkXJe4BSnjS5RO3ZrglsfnpOnonP49sLWXXaIN9gTIZg==
  template:
    metadata:
      name: zigbee2mqtt
      namespace: zigbee2mqtt
