apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-misc-extra-configs
  namespace: zigbee2mqtt
  labels:
    app.kubernetes.io/instance: zigbee2mqtt-misc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zigbee2mqtt
    app.kubernetes.io/version: 1.42.0
    argocd.argoproj.io/instance: zigbee2mqtt-misc
    helm.sh/chart: zigbee2mqtt-1.42.0
data:
  devices.yaml: |
    '0x60a423fffe035c19':
      debounce: 1
      friendly_name: poutre_dimmer
      homeassistant:
        last_seen:
          enabled_by_default: true
        linkquality:
          enabled_by_default: true
    '0x60a423fffe0381d2':
      debounce: 1
      friendly_name: bedroom_left_dimmer
      homeassistant:
        last_seen:
          enabled_by_default: true
        linkquality:
          enabled_by_default: true
    '0x00158d00013d350f':
      debounce: 1
      friendly_name: bedroom_left_remote
      homeassistant:
        last_seen:
          enabled_by_default: true
        linkquality:
          enabled_by_default: true
  groups.yaml: |
    '16388':
      devices:
        - '0x60a423fffe0381d2'
      friendly_name: group_bedroom_left
      optimistic: true
      retain: false
      transition: 2
    '16389':
      devices:
        - '0x60a423fffe035c19'
      friendly_name: group_living_poutre
      optimistic: true
      retain: false
      transition: 2
