keys:
  - &nas age1n8x9pwjy493xzsgdcedngajamdpwplr8777plxhehmh8e9xzcg6sr9qx9d
  - &iot age13g6z2pd7dsywgfw80356veqsrufzhrs8urzwklza5gptkcw8t9ss32y3zt
  - &nmaupu-laptop age170gy8t4y7rx5cwmfyeht4n7zemgq5yqdd8062gaevmyp9yd9e9qqnut4kw

creation_rules:
  - path_regex: secrets/nas\.yaml$
    key_groups:
      - age:
          - *nas
          - *nmaupu-laptop
  - path_regex: secrets/iot\.yaml$
    key_groups:
      - age:
          - *iot
          - *nmaupu-laptop
