---
ingress:
  main:
    enabled: true
    hosts:
      - host: bazarr.knas.home.fossar.net
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        certificateIssuer: google-dns-issuer-prod
        enabled: true
      traefik:
        allowCors: false
        enabled: true
        entrypoints:
          - websecure

global:
  traefik:
    fixedMiddlewares:
      - name: chain-basic
        namespace: ingress-controller
