---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: home-assistant
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: home-assistant
spec:
  staticConfigs:
    - targets: ['hass.home.fossar.net']
      labels:
        job: prometheus
  metricsPath: /api/prometheus
  scheme: HTTPS
  authorization:
    type: Bearer
    credentials:
      name: home-assistant-prometheus-token
      key: token

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-prometheus-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgA/asmonGXBHrkUonqQn0DAIyzYsS3v/xJrd2ZYWZv5dcT5BWIyBWKsgi9bPQmqw/UVqaMkGRjM+/QId+eYifAF/mU+9CptO5ejtN0tRYSk5X/LVKYHMrEkTvbCasaBDe9ykI9bXwk+oMm+iIl6elAcG/O/q7gc+QcacCRXvxIkp54yeIOkoO9IvTFgcHWWpDdhUIkmy3lZgSJF/mjt8RAq2ek0lNVj9tLjWzgDxiDaZfmByYfAKW8d8PWhc7GT1oOd8zdS74AWtUMse/g/CqkIRuRu1oYZRfZl4jn1wu1MgaQD3OhTmwHQ8BMrW2EnfOM4Ff9b0SkXex5c/nIKF+ipTsXqM6+GEFObgZUfiYMso5K1JYwjU6cZajjjb1MtnA1rbWtj6NgZLlkZ3qFkd7srh+cAFfPGSNK1fHdVNfUGdGuWHcEYjN5+T5a2pXKYXQ/jiRQ9VhIpryq/k4LVL2GthXFI7OJwys7DAPeHnDYCg401WNArFAgZhf77KQd2AJybmGATGDib0HLJlQ/rRiL9aZXsyZ7oZhbJ9XhprPjM8Z9s346Hl0AJguhPh96S256kd1ID0ihNF4TrUGuOfmO/jqwOd90TNRfLYpVvLJB33FkZ0JwbuPP/58mu3floH4ZhU+OJ0GTru7HoMqW62VF/Iavmt2pJczXuQX5MaiDjD2r6iDHTXH4RvldvOmaju+/pD1kF3H+cgqQc5Jd6YW825WpUtii0XL4suZQsmUVlqLdA/Lat48ZmqPwZ4bGN+Gl93q/3frR8YId7zlHGRSXhJvzVZjbEd/kd0A9HuPw/Zkcz/Y/2o1DuVsKOOhD3dCoPxlbHCzc/LOVXk9ua1F7hxCwdTFzlzUZgUh48+GDovlnqMzrbTDlY0lX996Vw7DCC967nw7WIIoxjOB3Veyyn1IgVmGA7VvC9Ro8XHadkU1joKBLn95w=
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-prometheus-token
      namespace: monitoring
    type: Opaque
