---
## Using layer 3 (BGP) install of layer 2 advertisement so
## that we don't overlay local LAN network.
## L2 old config is commented out as a reference.
## Mostly based on https://devpress.csdn.net/cloud/62f654497e6682346618b0b8.html

# L2Advertisements:
#   - name: l2adv
#     addressPools:
#       - apps

BGPAdvertisements:
  - name: bgpadv
    addressPools:
      - appsbgp
    aggregationLength: 24
    peers:
      - home-router

Peers:
  - name: home-router
    peerAddress: 192.168.12.1
    myASN: 66001
    peerASN: 65000

ipAddressPools:
  # - name: apps
  #   autoAssign: true
  #   avoidBuggyIPs: false
  #   addresses:
  #     - 192.168.12.100-192.168.12.150
  - name: appsbgp
    protocol: bgp
    autoAssign: "false"
    avoidBuggyIPs: "true"
    addresses:
      - 192.168.100.0/24

operator:
  metallb:
    namespace: metallb

portal:
  open:
    enabled: true

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 9999
