---
persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/tank/dls/configs/radarr
    targetSelector:
      main:
        main:
          mountPath: /config
      exportarr:
        exportarr:
          mountPath: /config
  online:
    enabled: true
    type: hostPath
    hostPath: /mnt/tank/dls
    mountPath: /mnt/dls

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 1001
    runAsGroup: 1001

ingress:
  main:
    enabled: true
    hosts:
      - host: radarr.knas.home.fossar.net
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        certificateIssuer: google-dns-issuer-prod
        enabled: true
      traefik:
        allowCors: false
        enabled: true
        entrypoints:
          - websecure

global:
  traefik:
    fixedMiddlewares:
      - name: chain-basic
        namespace: ingress-controller

workload:
  main:
    primary: true
    type: Deployment
    podSpec:
      containers:
        main:
          primary: true
          env:
            PUID: "1001"
            PGID: "1001"
          probes:
            liveness:
              enabled: true
              type: http
              path: /ping
              port: 7878
            readiness:
              enabled: true
              type: http
              path: /ping
              port: 7878
            startup:
              enabled: true
              type: http
              path: /ping
              port: 7878
  exportarr:
    enabled: true
    type: Deployment
    podSpec:
      containers:
        exportarr:
          enabled: true
          primary: true
          env:
            PUID: "1001"
            PGID: "1001"
          probes:
            liveness:
              enabled: true
              type: http
              path: /metrics
              port: 7878
            readiness:
              enabled: true
              type: http
              path: /metrics
              port: 7878
            startup:
              enabled: true
              type: http
              path: /metrics
              port: 7878

metrics:
  main:
    labels:
      release: kube-prometheus-stack
