---
image:
  repository: ghcr.io/home-operations/radarr
  pullPolicy: IfNotPresent
  tag: 5.26.2.10099
exportarrImage:
  repository: ghcr.io/onedr0p/exportarr
  pullPolicy: IfNotPresent
  tag: v2.3.0

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/tank/dls/configs/radarr
    targetSelector:
      main:
        main:
          mountPath: /config
      exportarr:
        exportarr:
          mountPath: /config
  online:
    enabled: true
    type: hostPath
    hostPath: /mnt/tank/dls
    mountPath: /mnt/dls

ingress:
  main:
    enabled: true
    hosts:
      - host: radarr.knas.home.fossar.net
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        certificateIssuer: google-dns-issuer-prod
        enabled: true
      traefik:
        allowCors: false
        enabled: true
        entrypoints:
          - websecure

global:
  traefik:
    fixedMiddlewares:
      - name: chain-basic
        namespace: ingress-controller

workload:
  main:
    primary: true
    type: Deployment
    podSpec:
      securityContext:
        fsGroup: 1001
      containers:
        main:
          primary: true
          probes:
            liveness:
              enabled: true
              type: http
              path: /ping
              port: 7878
            readiness:
              enabled: true
              type: http
              path: /ping
              port: 7878
            startup:
              enabled: true
              type: http
              path: /ping
              port: 7878
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
  exportarr:
    enabled: true
    type: Deployment
    podSpec:
      securityContext:
        fsGroup: 1001
      containers:
        exportarr:
          enabled: true
          primary: true
          probes:
            liveness:
              enabled: true
              type: http
              path: /metrics
              port: 9706
            readiness:
              enabled: true
              type: http
              path: /metrics
              port: 9706
            startup:
              enabled: true
              type: http
              path: /metrics
              port: 9706
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001

metrics:
  main:
    labels:
      release: kube-prometheus-stack
