---
image:
  repository: linuxserver/heimdall
  tag: 2.6.1@sha256:9bff1282379516220b39f27261d061f776dfe33cfca0502c03d03ca48f8ecaad
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        port: 10014
        targetPort: 80

ingress:
  main:
    enabled: true
    hosts:
      - host: heimdall.iot.home.fossar.net
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        certificateIssuer: google-dns-issuer-prod
        enabled: true
      traefik:
        allowCors: false
        enabled: true
        entrypoints:
          - websecure

global:
  traefik:
    fixedMiddlewares:
      - name: chain-basic
        namespace: ingress-controller

persistence:
  config:
    enabled: false
