---

- name: TFTP server installation
  apt:
    name: tftpd-hpa
    state: present

- name: TFTP server configuration
  template:
    src: templates/tftpd-hpa.j2
    dest: /etc/default/tftpd-hpa
    mode: 0644
    owner: root
    group: root
  notify:
    - restart tftpd-hpa

- name: Creating tftproot directory
  file:
    path: "{{tftproot_dir}}"
    state: directory
    mode: 0755
  notify:
    - restart tftpd-hpa

- name: Enable and start tftpd-hpa service
  service:
    name: tftpd-hpa
    state: started
    enabled: yes
