deployment:
  replicasCount: 1
  image:
    repository: docker.io/nmaupu/freenas-provisioner
    tag: 2.5
  imagePullPolicy: IfNotPresent
  args: []

storageclass:
  create: true
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  reclaimPolicy: Delete
  datasetParentName: tank
  shareAllowedNetworks: ""
  shareRetainPreExisting: true

resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 50Mi

freenas:
  username: TBD
  password: TBD
  host: TBD
  port: :443
  protocol: http
  allowInsecure: "false"
