apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
    spec:
      hostNetwork: {{ .Values.deployment.hostNetwork }}
      initContainers:
        - name: init-creds
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          command:
            - sh
            - -c
            - touch /mosquitto/creds; mosquitto_passwd -b /mosquitto/creds "${USERNAME}" "${PASSWORD}"
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: password
          volumeMounts:
            - name: mosquitto-creds
              mountPath: /mosquitto
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: {{ template "fullname" . }}
        ports:
          - containerPort: 1883
            name: "mqtt"
          - containerPort: 9090
            name: "websocket"
        volumeMounts:
          - name: mosquitto-conf
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
            readOnly: true
          - name: mosquitto-data
            mountPath: /mosquitto/data
            subPath: mosquitto/data
          - name: mosquitto-creds
            mountPath: /mosquitto
        {{- with .Values.deployment.probes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.deployment.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
        - name: mosquitto-creds
          emptyDir: {}
        - name: mosquitto-conf
          configMap:
            name: {{ template "fullname" . }}
        - name: mosquitto-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
