---

- name: Creating conf directory
  file:
    state: directory
    mode: 0755
    path: "{{deluge_conf_directory}}"

- name: Creating configuration files
  template:
    src: "{{item}}.j2"
    dest: "{{deluge_conf_directory}}/{{item}}"
    mode: 0644
  with_items:
    - core.conf
    - label.conf
