---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freenas-provisioner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freenas-provisioner.name" . }}
    helm.sh/chart: {{ include "freenas-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  # all values should be base64 encoded (ie: echo -n 'https' | base64)
  #
  # note that all values are relative to where the provisioner is running
  # ie: if running the provisioner directly on the FreeNAS server 'localhost'
  # would be a valid 'host' value

  # http|https
  # default: http
  protocol: {{ .Values.freenas.protocol | b64enc }}

  # default: localhost (for running the provisioner out of cluster directly on FreeNAS node)
  host: {{ .Values.freenas.host | b64enc }}

  # Note: using the ":" trick on the port to avoid being considered as a float64...
  # https://github.com/helm/helm/issues/1707
  # default: 80
  port: {{ .Values.freenas.port | replace ":" "" | b64enc }}

  # default: root (api is only available for root currently)
  username: {{ .Values.freenas.username | b64enc }}
  password: {{ .Values.freenas.password | b64enc }}

  # allow for self-signed/untrusted certs if using https
  # true|false
  # default: false
  allowInsecure: {{ .Values.freenas.allowInsecure | quote | b64enc }}
