---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "gonaomi.fullname" . }}-roms
  labels:
    app.kubernetes.io/name: {{ include "gonaomi.name" . }}
    helm.sh/chart: {{ include "gonaomi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}
