---
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 1001
    runAsGroup: 1001

ingress:
  main:
    enabled: true
    hosts:
      - host: bazarr.knas.home.fossar.net
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        certificateIssuer: google-dns-issuer-prod
        enabled: true
      traefik:
        allowCors: false
        enabled: true
        entrypoints:
          - websecure

global:
  traefik:
    fixedMiddlewares:
      - name: chain-basic
        namespace: ingress-controller

persistence:
  config:
    type: hostPath
    hostPath: /mnt/tank/dls/configs/bazarr
    mountPath: "/config"
  tmp:
    enabled: true
    medium: ""
  varlogs:
    enabled: true
    medium: ""
  varrun:
    enabled: true
    medium: ""
  movies:
    enabled: true
    type: hostPath
    hostPath: /mnt/tank/dls/plex/Movies
    mountPath: /mnt/movies
  tv:
    enabled: true
    type: hostPath
    hostPath: /mnt/tank/dls/plex/TVShows-sonaar/
    mountPath: /mnt/tv

workload:
  main:
    primary: true
    podSpec:
      containers:
        main:
          primary: true
          probes:
            liveness:
              enabled: true
              type: http
              path: /ping
              port: 6767
            readiness:
              enabled: true
              type: http
              path: /ping
              port: 6767
            startup:
              enabled: true
              type: http
              path: /ping
              port: 6767
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
