---
ingress:
  main:
    enabled: true
    hosts:
      - host: bazarr.knas.home.fossar.net
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        certificateIssuer: google-dns-issuer-prod
        enabled: true
      traefik:
        allowCors: false
        enabled: true
        entrypoints:
          - websecure

global:
  traefik:
    fixedMiddlewares:
      - name: chain-basic
        namespace: ingress-controller

persistence:
  config:
    type: hostPath
    hostPath: /mnt/tank/dls/configs/bazarr
    mountPath: "/config"
  tmp:
    enabled: true
    medium: ""
  varlogs:
    enabled: true
    medium: ""
  varrun:
    enabled: true
    medium: ""

workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
