---

- name: restart lightdm
  service:
    name: lightdm
    state: restarted

- name: recompile xmonad
  become: yes
  become_user: "{{me}}"
  shell: xmonad --recompile

- name: antigen apply
  become: yes
  become_user: "{{me}}"
  shell: |
    source "{{home}}/.antigen.zsh"
    antigen use oh-my-zsh
    {% for plugin in zsh_antigen.plugins %}
      antigen bundle {{plugin}}
    {% endfor %}
    antigen theme {{zsh_antigen.theme}}
    antigen apply
  args:
    executable: "{{zsh_bin}}"
