---

- name: restart lightdm
  service:
    name: lightdm
    state: restarted

- name: recompile xmonad
  become: yes
  become_user: "{{me}}"
  shell: xmonad --recompile

- name: antigen apply
  become: yes
  become_user: "{{me}}"
  shell: |
    source "{{home}}/.antigen.zsh"
    antigen use oh-my-zsh
    {% for line in zsh_antigen %}
      {{line}}
    {% endfor %}
    antigen apply
  args:
    executable: "{{zsh_bin}}"
