#!/usr/bin/env bash

[ -f .screenlayout/myscreens.sh ] && sudo xrandr --setprovideroutputsource 1 0 && .screenlayout/myscreens.sh
xrdb -merge ~/.Xresources
autocutsel -f -s CLIPBOARD -buttonup
#redshift-gtk &
ssh-agent &
pkill xscreensaver; xscreensaver -no-splash -no-capture-stderr &
wicd-client -t &
solaar &
stalonetray &
feh --bg-scale /usr/share/wallpapers/debian.png &
exec xmonad
