---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  destination:
    namespace: ingress-controller
    server: https://kubernetes.default.svc
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 39.0.6
      helm:
        releaseName: traefik
        valueFiles:
          - $values/k8s/argocd/nas/deploy/traefik/values.yaml
    - repoURL: https://github.com/nmaupu-org/auto-home.git
      targetRevision: master
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
