---
workload:
  main:
    replicas: 1

service:
  main:
    loadBalancerIP: 192.168.99.10
    externalTrafficPolicy: Local
  tcp:
    loadBalancerIP: 192.168.99.1
    externalTrafficPolicy: Local
    web:
      port: 80
      protocol: http
    websecure:
      port: 443
      protocol: https

metrics:
  main:
    enabled: false
