---
alertmanager:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

prometheus:
  enabled: true
  prometheusSpec:
    retention: 720d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 500Gi
    securityContext:
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
      fsGroup: 1001
      seccompProfile:
        type: RuntimeDefault
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: google-dns-issuer-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - p8s.knas.home.fossar.net
      - prometheus.knas.home.fossar.net
    paths:
      - /
    tls:
      - secretName: prometheus-general-tls
        hosts:
          - p8s.knas.home.fossar.net
          - prometheus.knas.home.fossar.net

grafana:
  admin:
    existingSecret: grafana-admin-creds
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: google-dns-issuer-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - grafana.knas.home.fossar.net
      - grafana.home.fossar.net
    paths:
      - /
    tls:
      - secretName: grafana-general-tls
        hosts:
          - grafana.knas.home.fossar.net
          - grafana.home.fossar.net
  sidecar:
    datasources:
      alertmanager:
        enabled: false
  # additionalDataSources:
  #   - name: Prom
  #     uid: prom
  #     type: prometheus
  #     url: http://{{ printf "%s-prometheus.monitoring" .Release.Name }}:9090
