---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: google-dns-issuer-staging
spec:
  acme:
    email: {{ .Values.email | quote }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: google-dns-issuer-staging
    solvers:
      - dns01:
          cloudDNS:
            project: {{ .Values.googleProjectId | quote }}
            serviceAccountSecretRef:
              name: google-dns01-solver
              key: google-key.json

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: google-dns-issuer-prod
spec:
  acme:
    email: {{ .Values.email | quote }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: google-dns-issuer-prod
    solvers:
      - dns01:
          cloudDNS:
            project: {{ .Values.googleProjectId | quote }}
            serviceAccountSecretRef:
              name: google-dns01-solver
              key: google-key.json
