---

- name: Installing curl
  apt:
    name: curl
    state: present

- name: Adding user matchbox
  user:
    name: matchbox
    state: present
    shell: /bin/false

- name: Creating matchbox directories
  file:
    path: "{{item}}"
    mode: 0755
    state: directory
    owner: matchbox
    group: matchbox
  with_items:
    - /etc/matchbox
    - /var/lib/matchbox
    - /var/lib/matchbox/assets

- name: Downloading and unpacking matchbox
  unarchive:
    src: "{{matchbox.url}}"
    dest: /usr/local
    remote_src: true

- name: Copying matchbox binary
  copy:
    src: /usr/local/matchbox-{{matchbox_version}}-{{matchbox_arch}}/matchbox
    dest: /usr/bin/matchbox
    mode: 0755
    owner: root
    group: root
    remote_src: true
  notify: restart matchbox

- name: Dowloading coreos asset
  shell: /usr/local/matchbox-{{matchbox_version}}-{{matchbox_arch}}/scripts/get-coreos stable {{coreos_version}} .
  args:
    chdir: /var/lib/matchbox/assets
    creates: /var/lib/matchbox/assets/coreos/{{coreos_version}}

- name: Generating gRPC API certificates
  shell: SAN=DNS.1:{{matchbox_dns}},IP.1:{{ansible_default_ipv4.address}} /usr/local/matchbox-{{matchbox_version}}-{{matchbox_arch}}/scripts/tls/cert-gen 
  args:
    chdir: /usr/local/matchbox-{{matchbox_version}}-{{matchbox_arch}}/scripts/tls
    creates: /usr/local/matchbox-{{matchbox_version}}-{{matchbox_arch}}/scripts/tls/server.key

- name: Copying gRPC certificates
  copy:
    src: /usr/local/matchbox-{{matchbox_version}}-{{matchbox_arch}}/scripts/tls/{{item.file}}
    dest: /etc/matchbox/{{item.file}}
    mode: "{{item.mode}}"
    owner: matchbox
    group: matchbox
    remote_src: true
  with_items:
    - { file: server.key, mode: "0600" }
    - { file: server.crt, mode: "0644" }
    - { file: ca.crt, mode: "0644" }
  notify: restart matchbox

- name: Copying systemctl script
  copy:
    src: /usr/local/matchbox-{{matchbox_version}}-{{matchbox_arch}}/contrib/systemd/matchbox.service
    dest: /etc/systemd/system
    mode: 0644
    owner: root
    group: root
    remote_src: true
  notify:
    - daemon-reload
    - restart matchbox

- name: Creating matchbox systemd override dir
  file:
    path: /etc/systemd/system/matchbox.service.d
    state: directory

- name: Configuring matchbox service
  copy:
    src: files/matchbox-service-override.conf
    dest: /etc/systemd/system/matchbox.service.d/override.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - daemon-reload
    - restart matchbox

- name: Enabling matchbox service
  service:
    name: matchbox
    enabled: yes
    state: started

- name: Creating pxe menu for CoreOS
  template:
    src: templates/coreos.include.j2
    dest: "{{tftproot_dir}}/bios/pxelinux.cfg/coreos.include"
    mode: 0644
