---

- name: Downloading debian-live iso
  get_url:
    url: "{{debian_live_iso.url}}"
    dest: "{{nginx_http_pxe_dir}}/isos/{{debian_live_iso.image_name}}"
    checksum: "{{debian_live_iso.checksum}}"

- name: mounting debian-live.iso
  mount:
    state: mounted
    fstype: iso9660
    opts: ro
    src: "{{nginx_http_pxe_dir}}/isos/{{debian_live_iso.image_name}}"
    path: "{{nginx_http_pxe_dir}}/debian-live"

- name: Creating pxe menu for debian-live
  template:
    src: templates/debian-live-xfce.include.j2
    dest: "{{tftproot_dir}}/bios/pxelinux.cfg/debian-live-xfce.include"
    mode: 0644
