torrentleech:
  username: "{{ lookup('vault', 'secret/torrentleech.org', 'username') }}"
  password: "{{ lookup('vault', 'secret/torrentleech.org', 'password') }}"

torrent:
  host: http://{{ lookup('vault', 'secret/deluge', 'daemon_server') }}:{{ lookup('vault', 'secret/deluge', 'daemon_port') }}/
  path: /mnt/incoming-sickrage
  username: "{{ lookup('vault', 'secret/deluge', 'daemon_username') }}"
  password: "{{ lookup('vault', 'secret/deluge', 'daemon_password') }}"
  label: sickrage

opensubtitles:
  username: "{{ lookup('vault', 'secret/opensubtitles.org', 'username') }}"
  password: "{{ lookup('vault', 'secret/opensubtitles.org', 'password') }}"
