---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    admin-password: AgAs2g8ezwd4B11JsGK3RzJvpKERAvFoCqksjH9mkTYXqIYDX9StIwdm5z8VbkzJ7aa4PJGM0zysvZsVs98Tsdj5RKPhK6dBtKUb303bIHKhkQfI6LLeI6lGR9ny8uNz3cWdVmAVNDuuWNecKULva0S/bJhPb2J+NpcvZl7+K6g/flKQdwCHIJaN3DYaWaePfxkD9SVX8aJcv1cPLQTuQzUV6GPgVFaN2R4UiFKaihrC5MIn5uKC8qmEJ5dUXCnpaocAGAkjOjFrnOOPzUes4qtLpf0tLlNr7cPKNMQdIA3IWZw41RL1LXIcg/ECzUCajqVSGEtechBwuf3STF1EIioOG32hlBXu7ndqpJIEpJPhWiUKTYGbI0H3HVaIgk5ZHlib+QyGU3CFTyH5TECOzvVwdaEkbILH33Y8/wgv2XAAwheSYENHAdh4jFL69ysSmU35uo2sAk8Xvhz+b+Yxnsg49R1xhmZbqzLYbAKrz05d6eaWY3TXY2jP4dYmZr8GQpGtDxaVg/QEunbgJnao0QpYCd86MTc/lT6EKpuk1kNqoutLRjk1HvHm970sNQnDMEDQnBuyF+n3JpkFKMpOVjEIbcX1OrLFQubfAzlaYM+prUlxxTsC+WVp+u0YfG96IoRIK4ZqaT9evWBB7MgbQbiuPogqp4neKoz4+8XM00Rk9s62/RMFVfgsGHDY3Mj85Bkpznkw3LF1s93kAzPilsqxNJzJYNBCutcZyFoB5hjYz8cGNm/mBN4T
    admin-user: AgAwEJrX8l0igI7gcr8jnzXZGYgPXeARJOyCUXlZtgu1pFa2lZRd2tgvkJIbVye6dW035oztttmHfrj5Es3qBA5mYHNZJnDQZwSMwZjmjMMyRxEuVQ4Zr73egoyGdIgKTXzwwWb8vKi8zkc6JO3j70L5XhWgiLpFs1trwtC82Txfuqg2jCvHXW5rRf0EfEGnAnjDoAI7KEvqP6R07CR3vVNp5v6vnyuK0tvKwtIY04JfE5TDviSPtf5WckJbCmIQpMgLXdCMtbGPOUeAXa+RjdFhfzXWunXOK1HLv303nC8kMKtR97gsGFox8sJ53f8/ohd2ZjEA6nKepBKW76KD/TNbaUwRrpK9RlEvcoXFPa4ji38p6je87SO2SX1yqRGB95tgZf9FEJth365RIrq/r3v+LElmgXHBpmXt/RR9FljVNoJrBkTVBV5ZJfQpDHDo5blShzeo31qqquWHOwAkK2tMdeXAtC4a0WFnCXGqrrhGddAD4ecGespPPKg5eGIHx8ler084A6xZaeUh6PYmYPd8XE+wLDsIDvfhyYPDrogUgGB50tvx78LrEZ9rOtuUcTB8bDI7SihmKkOykyRru6B45Rzj4NFV7c8ZtRnBLQZRMuX7/TgeFY58JV+OkI1GlY6r0tSy3zw2K3BfS3t+eUS/nbg7dNZf3/86tyVb7YJbjLlpzqeguGXYk+krZ0138ff2mkPYpg==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
