---
persistence:
  config:
    enabled: true
    mountPath: /config
    size: 100Mi

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_LEVEL: debug
            LOG_HTML: true
