apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mqtt-gateway.fullname" . }}
  labels:
{{ include "mqtt-gateway.labels" . | indent 4 }}
type: Opaque
data:
  address: {{ .Values.mqtt.address | b64enc }}
  username: {{ .Values.mqtt.username | b64enc }}
  password: {{ .Values.mqtt.password | b64enc }}
