---

- import_tasks: syslinux.yml
  tags: pxe-syslinux
- import_tasks: http-server.yml
  tags: pxe-http-server
- import_tasks: pxe-netboot.xyz.yml
  tags: pxe-netboot-xyz

- name: Adding rc.local script to mount iso at boot
  template:
    src: templates/openwrt-rc.local.j2
    dest: /etc/rc.local
    mode: 0555
  notify:
    - run rc.local
