---

- name: Dowloading syslinux binaries under {{ tmpdir }}
  unarchive:
    src: "{{ syslinux_baseurl }}/syslinux-{{ syslinux_version }}.tar.gz"
    dest: "{{ tmpdir }}"
    remote_src: true
    extra_opts:
      - --no-same-owner

- name: Creating some directories under {{tftproot_dir}}
  file:
    dest: "{{ tftproot_dir }}/{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - pxe
    - pxe/bios
    - pxe/bios/pxelinux.cfg
    - pxe/bios/ipxe-scripts
    - pxe/bios/grub-entries
    - pxe/efi
    - pxe/efi/ipxe-scripts

- name: Copying necessary files for syslinux
  copy:
    src: "{{ tmpdir }}/syslinux-{{ syslinux_version }}/{{ item.file }}"
    dest: "{{ tftproot_dir }}/pxe/{{ item.subpath }}"
    remote_src: true
  with_items:
    - file: bios/core/pxelinux.0
      subpath: bios
    - file: bios/core/lpxelinux.0
      subpath: bios
    - file: bios/com32/elflink/ldlinux/ldlinux.c32
      subpath: bios
    - file: bios/com32/menu/vesamenu.c32
      subpath: bios
    - file: bios/com32/lib/libcom32.c32
      subpath: bios
    - file: bios/com32/libutil/libutil.c32
      subpath: bios

- name: Dowloading and copying ipxe binary file
  get_url:
    url: "{{ ipxe_url }}/{{ item.file }}"
    dest: "{{ tftproot_dir }}/pxe/{{ item.subpath }}/{{ item.file }}"
    mode: 0755
  with_items:
    - file: ipxe.lkrn
      subpath: bios
    - file: ipxe.efi
      subpath: efi

- name: Creating pxelinux.cfg default config
  template:
    src: templates/pxelinux-default.j2
    dest: "{{ tftproot_dir }}/pxe/bios/pxelinux.cfg/default"
    mode: 0644

- name: Copying graphics.conf file
  copy:
    src: files/graphics.conf
    dest: "{{ tftproot_dir }}/pxe/bios/pxelinux.cfg/graphics.conf"
    mode: 0644

- name: Creating ipxe scripts
  template:
    src: templates/{{ item.file }}.j2
    dest: "{{ tftproot_dir }}/pxe/{{ item.subpath }}/ipxe-scripts/{{ item.file }}"
    mode: 0644
  with_items:
    - file: netboot.xyz.ipxe
      subpath: bios
      arch: lkrn
    - file: netboot.xyz.ipxe
      subpath: efi
      arch: efi

- name: Setting autoexec for EFI ipxe
  template:
    src: templates/autoexec.ipxe.j2
    dest: "{{ tftproot_dir }}/pxe/autoexec.ipxe"
    mode: 0644
