---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heimdall
  namespace: argocd
spec:
  project: default
  destination:
    namespace: heimdall
    name: in-cluster
  sources:
    - chart: heimdall
      repoURL: tccr.io/truecharts
      targetRevision: 22.1.4
      helm:
        releaseName: heimdall
        valueFiles:
          - $values/argocd/nas/deploy/heimdall/values.yaml
    - repoURL: https://github.com/nmaupu-org/auto-home.git
      targetRevision: master
      ref: values

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.hostUsers

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
