---

# After installation, create a /home/homeassistant/.hass-cli file containing
#   export HASS_SERVER=http://127.0.0.1:8123
#   export HASS_TOKEN=my_token
##
# Upgrade can be done using the following commands:
#   $ systemctl stop homeassistant
#   $ su - homeassistant
#   $ source /srv/homeassistant/bin/activate
#   $ python3 -m pip install --upgrade homeassistant
#   $ python3 -m pip install --upgrade homeassistant-cli
#   $ exit
#   $ systemctl start homeassistant
# https://www.home-assistant.io/docs/installation/virtualenv/
# https://www.ramoonus.nl/2019/10/23/how-to-install-python-3-8-on-raspberry-pi/

- name: Installing required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-bcrypt
    - python3-dev
    - python3-venv
    - python3-pip
    - libffi-dev
    - libssl-dev
    - libjpeg9-dev
    - zlib1g-dev
    - python-setuptools
    - jq
    - curl
    - avahi-daemon
    - dbus
    - socat
    - libxml2
    - libxslt1.1
    - ffmpeg
    - libatlas-base-dev
    - libavdevice-dev
    - libavdevice59
    - libavformat59

- name: Configuring server to Paris time
  timezone:
    name: Europe/Paris
  tags:
    - timezone
    - config
  notify:
    - restart homeassistant

- name: Ensuring modemmanager is uninstalled
  package:
    name: modemmanager
    state: absent

- name: Adding an account for home-assistant
  user:
    name: homeassistant
    groups: dialout,gpio,i2c
    append: yes
    system: yes

- name: Creating homeassistant directory
  file:
    path: /srv/homeassistant
    state: directory
    owner: homeassistant
    group: homeassistant
    mode: '0700'

- name: Copying create_password.py file
  copy:
    src: create_password.py
    dest: /srv/homeassistant/create_password.py
    owner: homeassistant
    group: homeassistant
    mode: '0700'

- name: Installing python virtualenv for homeassistant
  become: yes
  become_user: homeassistant
  become_method: sudo
  shell: |
    cd /srv/homeassistant
    python3 -m venv .
  args:
    creates: /srv/homeassistant/pyvenv.cfg

## Needed since hass v2021.10 to compile cryptography package for python
- name: Downloading rust install script
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rust.sh
    mode: '0755'

- name: Executing rust install script
  become: yes
  become_user: homeassistant
  become_method: sudo
  ansible.builtin.shell: /tmp/rust.sh -y --profile default
##

- name: Installing required python packages via pip
  become: yes
  become_user: homeassistant
  become_method: sudo
  pip:
    name:
      - wheel
      - homeassistant
      - homeassistant-cli
    virtualenv: /srv/homeassistant
    virtualenv_python: python3

- name: Preparing certs directory for homeassistant user
  file:
    path: /home/homeassistant/certs
    state: directory
    owner: homeassistant
    group: homeassistant
    mode: '0700'
  tags:
    - mount
    - config

- name: Adding update-hass-certs.sh script
  template:
    src: update-hass-certs.sh.j2
    dest: /usr/local/bin/update-hass-certs.sh
    owner: root
    group: root
    mode: '0755'
  tags:
    - mount
    - config
    - cron_cert

- name: Adding crontab to copy certs to homeassistant directory
  cron:
    name: "rsync certs directory from NFS to homeassistant"
    job: "/usr/local/bin/update-hass-certs.sh"
    hour: 2
  notify:
    - restart homeassistant
  tags:
    - mount
    - config
    - cron_cert

- name: Preparing configuration directory
  file:
    path: "/home/homeassistant/.homeassistant"
    state: absent
  notify:
    - restart homeassistant
  tags:
    - config

- name: Creating .homeassistant directory
  file:
    path: /home/homeassistant/.homeassistant
    state: directory
    mode: '0700'
    owner: homeassistant
    group: homeassistant
  notify:
    - restart homeassistant
  tags:
    - config

- name: Creating secrets.yaml file
  become: yes
  become_user: homeassistant
  become_method: sudo
  copy:
    content: |
      {{ hass.secrets_yaml }}
    dest: /home/homeassistant/.homeassistant/secrets.yaml
  notify:
    - restart homeassistant
  tags:
    - config

- name: Creating .storage directory
  become: yes
  become_user: homeassistant
  become_method: sudo
  file:
    state: directory
    path: /home/homeassistant/.homeassistant/.storage
    owner: homeassistant
    group: homeassistant
    mode: '0700'
  tags:
    - config

- name: Creating .storage/onboarding file
  become: yes
  become_user: homeassistant
  become_method: sudo
  copy:
    src: onboarding
    dest: /home/homeassistant/.homeassistant/.storage/onboarding
    mode: '0644'
  tags:
    - config

- name: hashing default user password
  shell: |
    /srv/homeassistant/create_password.py
  args:
    stdin: "{{ hass.defaults.user.password }}"
  register: passwd_hash
  tags:
    - config

- name: Creating .storage/auth_provider.homeassistant file
  template:
    src: auth_provider.homeassistant.j2
    dest: /home/homeassistant/.homeassistant/.storage/auth_provider.homeassistant
    owner: homeassistant
    group: homeassistant
    mode: '0600'
  vars:
    pwd: "{{ passwd_hash.stdout }}"
  notify:
    - restart homeassistant
  tags:
    - config

- name: Creating plugins directories
  become: yes
  become_user: homeassistant
  become_method: sudo
  file:
    path: "/home/homeassistant/.homeassistant/{{ item }}"
    state: directory
  with_items:
    - www
    - www/icons/weather_icons
    - www/community/lovelace-meteofrance-weather-card/icons
  notify:
    - restart homeassistant
  tags:
    - config
    - hass-plugins
    - other-plugins

- name: Adding background images
  copy:
    src: files/hass-theme-background.jpg
    dest: /home/homeassistant/.homeassistant/www/day.jpg
    owner: homeassistant
    group: homeassistant
    mode: '0644'
  tags:
    - config
    - hass-plugins

- name: Getting third-party plugins
  become: yes
  become_user: homeassistant
  become_method: sudo
  git:
    repo: "{{ item.repo }}"
    dest: "/home/homeassistant/.homeassistant/www/{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - repo: https://github.com/thomasloven/lovelace-auto-entities.git
      name: auto-entities
      version: "1.12.1"
    - repo: https://github.com/thomasloven/lovelace-template-entity-row
      name: template-entity-row
      version: "1.3.2"
    - repo: https://github.com/rodrigofragadf/lovelace-cards.git
      name: lovelace-cards
      version: "c246a4f960d94f4adc6658f6268391caf5716e6a" # committed on Jan 6, 2019
    - repo: https://github.com/thomasloven/lovelace-layout-card.git
      name: lovelace-layout-cards
      version: "2.4.4"
  notify:
    - restart homeassistant
  tags:
    - config
    - hass-plugins

- name: Getting other plugins
  get_url:
    url: "{{ item.url }}"
    dest: "/home/homeassistant/.homeassistant/www/{{ item.name }}"
    owner: homeassistant
    group: homeassistant
    mode: '0644'
  with_items:
    - url: https://github.com/maykar/custom-header/releases/download/1.3.2/custom-header.js
      name: custom-header.js
    - url: https://github.com/kalkih/mini-graph-card/releases/download/v0.9.2/mini-graph-card-bundle.js
      name: mini-graph-card-bundle.js
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/meteofrance-weather-card.js
      name: community/lovelace-meteofrance-weather-card/meteofrance-weather-card.js
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/meteofrance-weather-card-editor.js
      name: community/lovelace-meteofrance-weather-card/meteofrance-weather-card-editor.js
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/cloudy-day-3.svg
      name: community/lovelace-meteofrance-weather-card/icons/cloudy-day-3.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/cloudy-night-3.svg
      name: community/lovelace-meteofrance-weather-card/icons/cloudy-night-3.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/cloudy.svg
      name: community/lovelace-meteofrance-weather-card/icons/cloudy.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/day.svg
      name: community/lovelace-meteofrance-weather-card/icons/day.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/fog.svg
      name: community/lovelace-meteofrance-weather-card/icons/fog.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/lightning-rainy.svg
      name: community/lovelace-meteofrance-weather-card/icons/lightning-rainy.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/night.svg
      name: community/lovelace-meteofrance-weather-card/icons/night.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/rainy-5.svg
      name: community/lovelace-meteofrance-weather-card/icons/rainy-5.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/rainy-6.svg
      name: community/lovelace-meteofrance-weather-card/icons/rainy-6.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/rainy-7.svg
      name: community/lovelace-meteofrance-weather-card/icons/rainy-7.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/snowy-6.svg
      name: community/lovelace-meteofrance-weather-card/icons/snowy-6.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/snowy-rainy.svg
      name: community/lovelace-meteofrance-weather-card/icons/snowy-rainy.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/thunder.svg
      name: community/lovelace-meteofrance-weather-card/icons/thunder.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/windy-night.svg
      name: community/lovelace-meteofrance-weather-card/icons/windy-night.svg
    - url: https://raw.githubusercontent.com/hacf-fr/lovelace-meteofrance-weather-card/Meteo-France/dist/icons/windy.svg
      name: community/lovelace-meteofrance-weather-card/icons/windy.svg
  notify:
    - restart homeassistant
  tags:
    - config
    - hass-plugins
    - other-plugins

- name: Installing AM chart icons (animated weather icons)
  unarchive:
    src: https://download.amcharts.com/1.0/amcharts_weather_icons_1.0.0.zip
    dest: /home/homeassistant/.homeassistant/www/icons/weather_icons/
    remote_src: true
    owner: homeassistant
    group: homeassistant
  notify:
    - restart homeassistant
  tags:
    - config
    - hass-plugins

- name: Getting configuration via git
  become: yes
  become_user: homeassistant
  become_method: sudo
  shell: |
    set -e
    cd /home/homeassistant/.homeassistant
    git init
    git remote add origin https://github.com/nmaupu/hass-config.git
    git pull origin master
    git branch --set-upstream-to=origin/master master
  args:
    creates: /home/homeassistant/.homeassistant/.git/config
  notify:
    - restart homeassistant
  tags:
    - config

- name: Installing systemd configuration file
  copy:
    src: files/systemd.conf
    dest: /etc/systemd/system/homeassistant.service
    owner: root
    group: root
    mode: '0755'

- name: Enabling homeassistant service
  systemd:
    name: homeassistant
    daemon_reload: yes
    enabled: yes
    state: started

- name: Installing crontab script to auto update GIT repo
  copy:
    src: files/update-hass-config.sh
    dest: /usr/local/bin/update-hass-config.sh
    owner: root
    group: root
    mode: '0755'
  tags:
    - config
    - config_git

- name: Installing GIT auto-update crontab
  cron:
    name: "Auto update Home Assistant configuration from git"
    state: present
    user: homeassistant
    job: "/usr/local/bin/update-hass-config.sh"
  tags:
    - config
    - config_git
