---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  destination:
    namespace: metallb
    name: in-cluster
  sources:
    - chart: metallb
      repoURL: tccr.io/truecharts
      targetRevision: 16.1.1
      helm:
        releaseName: metallb
        valueFiles:
          - $values/argocd/nas/deploy/metallb/values.yaml
    - repoURL: https://github.com/nmaupu-org/auto-home.git
      targetRevision: master
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
