---
replicaCount: 1

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: google-dns-issuer-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: headlamp.iot.home.fossar.net
      paths:
        - path: /
          type: Prefix
  tls:
    - secretName: headlamp-tls
      hosts:
        - headlamp.iot.home.fossar.net

config:
  pluginsDir: /headlamp/plugins
  extraArgs:
    - --in-cluster
