---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt-gateway.fullname" . }}
  labels:
{{ include "mqtt-gateway.labels" . | indent 4 }}
data:
  mqttgateway-config.yaml: |-
    {{- .Values.mqttgateway.config | nindent 4 }}
