{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mqtt-gateway.serviceAccountName" . }}
  labels:
{{ include "mqtt-gateway.labels" . | indent 4 }}
{{- end -}}
