---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "freenas-provisioner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freenas-provisioner.name" . }}
    helm.sh/chart: {{ include "freenas-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "freenas-provisioner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freenas-provisioner.name" . }}
    helm.sh/chart: {{ include "freenas-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "freenas-provisioner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freenas-provisioner.name" . }}
    helm.sh/chart: {{ include "freenas-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "freenas-provisioner.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "freenas-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "freenas-provisioner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freenas-provisioner.name" . }}
    helm.sh/chart: {{ include "freenas-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "create", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "freenas-provisioner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freenas-provisioner.name" . }}
    helm.sh/chart: {{ include "freenas-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "freenas-provisioner.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "freenas-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
