---
# ingress:
#   main:
#     enabled: true
#     hosts:
#       - host: p8s.knas.home.fossar.net
#         paths:
#           - path: /
#             pathType: Prefix
#     integrations:
#       certManager:
#         certificateIssuer: google-dns-issuer-prod
#         enabled: true
#       traefik:
#         allowCors: false
#         enabled: true
#         entrypoints:
#           - websecure
#
# global:
#   traefik:
#     fixedMiddlewares:
#       - name: chain-basic
#         namespace: ingress-controller

alertmanager:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
prometheus:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: google-dns-issuer-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - p8s.knas.home.fossar.net
      - prometheus.knas.home.fossar.net
    paths:
      - /
    tls:
      - secretName: prometheus-general-tls
        hosts:
          - p8s.knas.home.fossar.net
          - prometheus.knas.home.fossar.net
