---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hass-secrets
  namespace: hass
spec:
  encryptedData:
    secret.yaml: AgDfd9Pcug2SUW8LJIlG/BV4QNn9QLcGgArvwaXiBNEragx7ll1yK9AomNe9MoB+oQjd3od7fuhA2N7Zaz3MTobDbVKo8Zq4gCe+aW48hDqUw8nic4f5foXxBz7p7loadIcr9UebYzeTu4txlpPGaStF6ccp/OAn8Yhf4WsRdgudAeRJY/nmKpqT/+V22vbxDYD6ZmTKpyP4WrztDt0ZWiH+FHzVdcrprKEXDrJ6SK0quk9dsvnfVZsJBGkizsFZvSMSin+qEyQ1PNaizEbTu55npFJ9csEUL/YiR7yjc2gjo1AnXY6eaRYjr1faJv0ORIN+vx5OuYioWEZUdkAiS69t5Pz0dbkurV/e4NKz3sL1KSICoOdJOysrIhdZkV+cv0kHEjMIRLpRIHQ+EE7+6bM+3JeymS+eCSS7ehBR2zVOWsEU/GuLQVO0KP8MsW7tzbH3jWwuPuVvhHnLJCRz4V/oS/SZaJ69YipVs1GUgmA/2zu/HryQfaahIYk8pwtxomgcpnHtEKTHXhL+GB06WbkkPAzttZ9ocw01UzY1GNfrtL6FpGF7FmpqJQzKLjA6S+wVRrBaOf75ehUBRlyeqxnm8qUMxJ0ON3A3YFU4Mfbu62IRcq5qjG85kydnNIUXbqr3L2NY5J/dTPwL2sGF8psMilYOy3K97L30zWiODNl8CsEkBv8q+rZ5ZyjFTGaamsnWE8DIP02DHGv0ERzA562+ssgxkOpUCQzy4wtDOIZwETABl1aebrf3pN4yemvXZN0pVWHGAz81Ej99Hrl656nh9o9+3955xK70wTKa9pch1wH14e+tEXdq4S+G1/bTvyGQYjH7t/bgqL245Q2GSdtNfhhMoHetzNMpUYQFPxrvwsEbSUtJzlS272hn+j3gPdIg+pXJ46YxRv2TxVMB/VDeIcmC4FnBDxmkc75BYdu5asLybYUsTjmt
  template:
    metadata:
      name: hass-secrets
      namespace: hass
