---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mosquitto-passwordfile
  namespace: mosquitto
spec:
  encryptedData:
    passwordfile: AgB0Akcfr67s4lQmwJ4b8tsWnIOVDOQ6N2DlUEo4CJwH9kUb9eW44fO2vxWHbtyYy4pGAAgKzzPSdU96FLhMYjLBVBHpV+Sf/BuEFUfiCga/UlMagiI8q6GD36WRyzK7/PAJ/2z0VdqZQaZQ6JVObfnMNXSRbVsIogh9KUk9qyRLhYniuUOdDIhNPXadpjgXOsDu13KeVa1WDlD2JhMHdibptIJs82KNqx+TziuYXrKOxa1zhEMF9Oe7c58mAKoIgoZbKgWXIHto4vg/SG6A8t7B6jGJg+sKtEG3vasFLe9Uay4Abs3mfHl7dD08ZT6vC43U655ESt3nTuNJAPcNLaFfmwHs3g8NqlY15qHkutLwBpr3rTBnLBYJ+VYH8olSGSNRfS3sEtCXSSqoLdmaEBaFaKyi5Oa9PpIN1nSeEDpmlk840UWkXqocYKs7BJhWOukxfqd/c8CxccG6axUEEKzxdM1gKTpywubaV3uy8b1Dv2BzvGCZbkPwcc6Gyz1xwDEqW8G47TYAwRykFG0rugWR/crK13DhoIraJbdICR9Rux+4Ftc9Ea+FEPkyVw5pzsxQhLUzTTDEeGcCGribbDmj3I4J2bMORGjrIBCXctMmLdZLRTkXVBaf8r1WEHPiDmenrZMOHjgZXzOmbFf503mXA+Sr6L5hVN4t27YncpE+gyXQGCAg3xO1pRZpASVQVv7rp1GZnyruQE/+hXWovixRgb/5oR1hDH+CZb+/CuMjX6jUaVr38G1fM0+/PcL5874OuYGo56GTUkr8DDrnzZ4dGgLgFRO/ohHfHcZf6cTCyeikSFgmt0M7v/xSyvW+q9styvjN07X6NJ3gRzQK9a9n6ZkWnfCd
  template:
    metadata:
      name: mosquitto-passwordfile
      namespace: mosquitto
