---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iot.fullname" . }}
data:
  username: {{ .Values.mqtt.username | b64enc }}
  password: {{ .Values.mqtt.password | b64enc }}
  host:     {{ .Values.mqtt.host | b64enc }}
