---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  encryptedData:
    secret.yaml: AgCbKcDgoMowy/oSO0Htzik1WFdV1wsT7rIM82nVjEOLgy4jyLWL5nyDkawxR+7/F/vzcpGQN6kPWIf63Os3qYh6ptrRnj0vpwZDhSW/egLN7K3TsFAlF7/aOq9aqA8mfERvefL43MdFsaETzySThVTfMhF/3dJw1Q69k4MKYaUwZzRucTQSzDgriuNMSW6tZ2/M8aLUIyWmvFvkTVr1uRFd/jadapOU9KfpndWRTdsAOdkr0RLbnANV7WIOYM/mLjfGl9xlY1JHEpFpeUgQgT+UazklYHTVMvKKH6ijgb1IC2Ctm/AQwFha2Du2iGQhxfyILuKtSPWeZBVozHjFZff0eQyg9k4WKqC2iXjCJlSwP2S599gLl4/nHXZTpa/1xc6so8UVhHO0o+pOkyvFSdYk9cc8M+RHqd9BX4t1wFG1HCewroC3OIF+75iu6+3Tec9nBlfQUIATybZrqcx4KBge618cPgmoran3NfI9rljAltS+P6gNhhq3FyZwuS0AeZNqyT/Py6BOvDOirhZ3sDSc+SC7OqNChRRdCOOcpDkzxiTF2ExYISPg+vOBtjA3jE4/8NQpfDnSpAgszlOuvzgKrHpgRA6nzGGszbNe6Sd3RrQRtblJfNcWWeDDSF6i/lVCmZ8M1JlPklAKpbNRg2zF8lFxAwbjGqV8gB18yDTVmtCFAnSdHESa1914513D48TCexfBTnxeC4Lvn0steEn9paRBdT9B8+g2DpwY5GW2ah6VSO//yys4kd9fTeetpXt41RO7IglhlRoRN69RzMyVRv8Kg2WHYSvfDJpV53KSQ0ncW+9WgnKLJiOsefo=
  template:
    metadata:
      creationTimestamp: null
      name: zigbee2mqtt
      namespace: zigbee2mqtt
    type: Opaque
