---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring
    name: iot
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 61.2.0
      helm:
        releaseName: iot-kube-prometheus-stack
        valueFiles:
          - $values/k8s/argocd/iot/deploy/monitoring/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/nmaupu-org/auto-home.git
      targetRevision: master
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
