---
image:
  repository: linuxserver/heimdall
  tag: 2.6.1@sha256:9bff1282379516220b39f27261d061f776dfe33cfca0502c03d03ca48f8ecaad
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        port: 10014
        targetPort: 80

ingress:
  main:
    enabled: true
    hosts:
      - host: dashboard.home.fossar.net
        paths:
          - path: /
            pathType: Prefix
      - host: heimdall.knas.home.fossar.net
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        certificateIssuer: google-dns-issuer-prod
        enabled: true
      traefik:
        allowCors: false
        enabled: true
        entrypoints:
          - websecure

global:
  traefik:
    fixedMiddlewares:
      - name: chain-basic
        namespace: ingress-controller

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/tank/dls/configs/heimdall

# To change the GID, need to set fsGroup
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
  pod:
    fsGroup: 1001

# UID can be changed using fixedEnv (for GID, using fsGroup above)
workload:
  main:
    podSpec:
      containers:
        main:
          fixedEnv:
            PUID: 1001
            USER_ID: 1001
            UID: 1001
            PGID: 1001
            GROUP_ID: 1001
            GID: 1001
