---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: default
  destination:
    namespace: descheduler
    server: https://kubernetes.default.svc
  sources:
    - chart: descheduler
      repoURL: https://kubernetes-sigs.github.io/descheduler/
      targetRevision: 0.35.1
      helm:
        releaseName: descheduler
        values: |
          kind: Deployment
          deschedulingInterval: 5m
          deschedulerPolicy:
            profiles:
              - name: default
                plugins:
                  deschedule:
                    enabled:
                      - RemovePodsViolatingNodeAffinity
                pluginConfig:
                  - name: RemovePodsViolatingNodeAffinity
                    args:
                      nodeAffinityType:
                        - requiredDuringSchedulingIgnoredDuringExecution
                        - preferredDuringSchedulingIgnoredDuringExecution
    - repoURL: https://github.com/nmaupu-org/auto-home.git
      targetRevision: master
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
