---

- name: Installing some packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - vim
    - rsync
    - htop
    - git
    - tmux
    - "{{linux_base_extra_packages}}"

- name: Ensure .ssh directories exist
  file:
    path: "{{item.home}}/.ssh"
    state: directory
    mode: 0700
    owner: "{{item.user}}"
    group: "{{item.user}}"
  with_items: "{{users}}"

- name: SSH public keys
  copy:
    content: |
      {{authorized_keys}}
    dest: "{{item.home}}/.ssh/authorized_keys"
    owner: "{{item.user}}"
    group: "{{item.user}}"
    mode: 0644
  with_items: "{{users}}"
  tags: authorized_keys
