---

- name: Installing some packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - vim
    - rsync
    - htop
    - git
    - tmux
    - "{{linux_base_extra_packages}}"

- name: Ensuring users are existing
  user:
    name: "{{item.user}}"
    shell: "{{item.shell}}"
    groups: "{{item.extra_groups}}"
    append: yes
    state: present
    generate_ssh_key: "{{item.generate_ssh_key}}"
    ssh_key_bits: 2048
    ssh_key_file: ".ssh/id_rsa"
  with_items: "{{users}}"
  register: userscomputed
  tags: users

- name: Ensure .ssh directories exist
  file:
    path: "{{item.home}}/.ssh"
    state: directory
    mode: 0700
    owner: "{{item.user}}"
    group: "{{item.user}}"
  with_items: "{{users}}"
  tags: users

# Iterate through register variable to get ssh_public_key
# from current user
- name: SSH public keys
  blockinfile:
    block: |
      {{authorized_keys}}
      {% if item.ssh_public_key is defined %}
      {{item.ssh_public_key}}
      {% endif %}
    create: yes
    path: "{{item.item.home}}/.ssh/authorized_keys"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    owner: "{{item.item.user}}"
    group: "{{item.item.user}}"
    mode: 0644
  with_items: "{{userscomputed.results}}"
  tags:
    - users
    - authorized_keys
