---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: freenas-provisioner-secret
type: Opaque
data:
  username: {{ .Values.freenas.username | b64enc }}
  password: {{ .Values.freenas.password | b64enc }}

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Release.Name }}-deploy
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}-deploy
  replicas: {{ .Values.deployment.replicasCount }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}-deploy
    spec:
      containers:
      - name: freenas-provisioner
        image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        args:
{{ .Values.deployment.args | toYaml | indent 10 }}
        resources:
           limits:
             cpu: {{ .Values.resources.limits.cpu }}
             memory: {{ .Values.resources.limits.memory }}
           requests:
             cpu: {{ .Values.resources.requests.cpu }}
             memory: {{ .Values.resources.requests.memory }}
        env:
          - name: IDENTIFIER
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: FREENAS_HOST
            value: {{ .Values.freenas.host }}
          - name: FREENAS_PORT
            value: "{{ .Values.freenas.port }}"
          - name: FREENAS_PARENT_DATASET
            value: "{{ .Values.freenas.parentDataset }}"
          - name: FREENAS_USER
            valueFrom:
              secretKeyRef:
                name: freenas-provisioner-secret
                key: username
          - name: FREENAS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: freenas-provisioner-secret
                key: password
