---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-statics
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    name: iot
  sources:
    - path: ./k8s/argocd/iot/statics
      repoURL: https://github.com/nmaupu-org/auto-home.git
      targetRevision: master
      directory:
        recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
