replicaCount: 1

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: role
              operator: In
              values:
                - worker

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: google-dns-issuer-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: headlamp.apps.home.fossar.net
      paths:
        - path: /
          type: Prefix 
    - host: headlamp.home.fossar.net
      paths:
        - path: /
          type: Prefix
  tls:
    - secretName: headlamp-tls
      hosts:
        - headlamp.home.fossar.net
        - headlamp.apps.home.fossar.net

config:
  pluginsDir: /headlamp/plugins
  extraArgs:
    - --in-cluster
