---
# Add dnsmasq instances

- name: "Add dnsmasq instance"
  uci:
    command: add
    config: dhcp
    type: dnsmasq
  notify: restart dhcp

- name: "Set dnsmasq instance's configuration"
  uci:
    command: set
    key: dhcp.@dnsmasq[-1]
    value: "{{ outer_item.options }}"
  notify: restart dhcp

- name: "Set dnsmasq instance's list configuration"
  uci:
    command: add_list
    key: dhcp.@dnsmasq[-1].address
    value: "{{ item }}"
  loop: "{{ outer_item.addresses }}"
  notify: restart dhcp

- name: "Creating dnsmasq custom confdir"
  file:
    state: directory
    mode: 0755
    path: /etc/dnsmasq.d
  notify: restart dhcp

- name: "Copying dnsmasq custom boot configuration"
  template:
    src: templates/dnsmasq-boot-pxe.conf.j2
    dest: /etc/dnsmasq.d/boot-pxe.conf
    mode: 0644
  vars:
    server_address: "{{ firewall_network_interfaces.lan.ipaddr }}"
    # Those hard-coded files will be available when openwrt_pxe is executed
    pxe_files:
      efi: efi/ipxe.efi
      bios: bios/pxelinux.0
  notify: restart dhcp

- name: "Set dnsmasq external configuration for boot"
  uci:
    command: set
    key: dhcp.@dnsmasq[-1].confdir
    value: /etc/dnsmasq.d
  notify: restart dhcp
