---
# Add dnsmasq instances

- name: "Add dnsmasq instance"
  uci:
    command: add
    config: dhcp
    type: dnsmasq
  notify: restart dhcp

- name: "Set dnsmasq instance's configuration"
  uci:
    command: set
    key: dhcp.@dnsmasq[-1]
    value: "{{ outer_item.options }}"
  notify: restart dhcp

- name: "Set dnsmasq instance's list configuration"
  uci:
    command: add_list
    key: dhcp.@dnsmasq[-1].address
    value: "{{ item }}"
  loop: "{{ outer_item.addresses }}"

- name: "Add boot option"
  uci:
    command: add
    config: dhcp
    type: boot
  notify: restart dhcp

- name: "Set boot options"
  uci:
    command: set
    key: dhcp.@boot[-1]
    value:
      filename: pxelinux.0
      serveraddress: "{{ firewall_network_interfaces.lan.ipaddr }}"
      servername: OpenWrt
      force: 1
  notify: restart dhcp

- name: "Set dhcp_option list"
  uci:
    command: add_list
    key: dhcp.@boot[-1].dhcp_option
    value: 209,pxelinux.cfg/default
  notify: restart dhcp
