---

tftproot_dir: /var/lib/tftproot
tmpdir: /tmp
tftpd_opts: -4 --secure -v -v -v

pxe_http_server: "{{ ansible_default_ipv4.address }}"

## Released images don't support https, using a custom one
# ipxe_url: http://boot.ipxe.org
ipxe_url: https://github.com/nmaupu/ipxe-docker-compile/releases/download/v0.0.1

talos_version: 1.8.3
talos_baseurl: https://factory.talos.dev/image/f892bcd627ef28c5718b7b394ebe287ea7fbfe901f4e183c73e748cd1e1b5dee/v{{ talos_version }}

nginx_http_dir: /var/www
nginx_http_pxe_url: pxe
nginx_http_pxe_dir: "{{ nginx_http_dir }}/{{ nginx_http_pxe_url }}"
nginx_port: 8080
