---

tftproot_dir: /var/lib/tftproot
tmpdir: /tmp
tftpd_opts: -4 --secure -v -v -v

syslinux_version: 6.03
syslinux_url: https://www.kernel.org/pub/linux/utils/boot/syslinux/Testing/{{syslinux_major_ver}}
syslinux_baseurl: https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux

pxe_timeout: 60
pxe_title: PXE
pxe_http_server: "{{ ansible_default_ipv4.address }}"

pxe_menu_items:
  - netboot.xyz.include

ipxe_url: http://boot.ipxe.org

nginx_http_dir: /var/www
nginx_http_pxe_url: /pxe
nginx_http_pxe_dir: "{{ nginx_http_dir }}/{{ nginx_http_pxe_url }}"
nginx_port: 8080
