---

- name: Installing packages
  opkg:
    name: "{{item}}"
    state: present
  with_items: "{{ firewall_packages }}"

# uci handling
- name: Revert pending changes
  uci:
    command: revert

##
# Redirect and ports opening
- name: Deleting all redirect rules
  uci:
    command: delete
    key: firewall.@redirect[0]
  register: result
  until: result.failed | bool
  delay: 0
  retries: 99
  ignore_errors: true

- name: Add firewall redirect
  include_tasks: uci_redirect.yaml
  loop: "{{ firewall_ports }}"

##
# Commit uci changes
- name: commit changes
  uci:
    command: commit
  notify: restart firewall
