---

- name: Installing packages
  opkg:
    name: "{{item}}"
    state: present
  with_items: "{{ firewall_packages }}"

# uci handling
- name: Revert pending changes
  uci:
    command: revert

- name: Processing redirect rules
  include_tasks: redirects.yaml

- name: Processing DHCP/DNS configuration
  include_tasks: dhcp-dns.yaml

##
# Commit uci changes
- name: commit changes
  uci:
    command: commit
  notify: restart firewall
