---

##
## Packages

- name: Installing packages
  opkg:
    name: "{{item}}"
    state: present
  with_items: "{{ firewall_packages }}"

##
## UCI stuff

- name: Revert potential pending changes if needed
  uci:
    command: revert

- name: Processing DHCP configuration
  include_tasks: dhcp.yaml
  with_dict: "{{ firewall_dhcp }}"

- name: Processing redirect rules
  include_tasks: redirects.yaml

- name: Commit UCI changes
  uci:
    command: commit
