---

##
## Packages

- name: Installing packages
  opkg:
    name: "{{item}}"
    state: present
  with_items: "{{ firewall_packages }}"

##
## UCI stuff

- name: Processing DHCP configuration
  include_tasks: dhcp-server.yaml
  with_dict: "{{ firewall_dhcp }}"

- name: Processing DHCP static leases configuration
  include_tasks: dhcp-static-leases.yaml

- name: Processing DNS entries
  include_tasks: dns.yaml

- name: Processing redirect rules
  include_tasks: redirects.yaml
