---
# Group of tasks to add a redirection to the firewall
# Parameter: dictionary containing the values to add (as a loop)

- name: "{{ item.name }} - Add a new redirect rule"
  uci:
    command: add
    config: firewall
    type: redirect
  notify: restart firewall

- name: "{{ item.name}} - Set redirect configuration"
  uci:
    command: set
    key: firewall.@redirect[-1]
    value: "{{ item }}"
  notify: restart firewall
