apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
subsets:
  - addresses:
      - ip: {{ .Values.hostIP | required ".Values.hostIP is required" | quote }}
    ports:
      - port: {{ .Values.hostPort }}
