---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: le-certs-sync
  namespace: argocd
  labels:
    app.kubernetes.io/instance: custom-external-certs
    argocd.argoproj.io/instance: custom-external-certs

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: le-certs-sync-role
  namespace: argocd
  labels:
    app.kubernetes.io/instance: custom-external-certs
    argocd.argoproj.io/instance: custom-external-certs
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: le-certs-sync-rolebinding
  namespace: argocd
  labels:
    app.kubernetes.io/instance: custom-external-certs
    argocd.argoproj.io/instance: custom-external-certs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: le-certs-sync-role
subjects:
  - kind: ServiceAccount
    name: le-certs-sync
    namespace: argocd

