---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homeassistant
  namespace: argocd
  labels:
    app.kubernetes.io/instance: custom-external-certs
    argocd.argoproj.io/instance: custom-external-certs
spec:
  dnsNames:
    - hass.home.fossar.net
    - homeassistant.home.fossar.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: google-dns-issuer-prod
  privateKey:
    rotationPolicy: Always
  secretName: homeassistant-cert
  secretTemplate:
    labels:
      nmaupu/cert: external
