apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "gonaomi.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gonaomi.name" . }}
    helm.sh/chart: {{ include "gonaomi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gonaomi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gonaomi.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --address={{ .Values.gonaomi.address }}
            - server
            - --listen-port={{ .Values.service.port }}
            - --roms-path={{ .Values.gonaomi.romsPath }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - name: roms-volume
              mountPath: {{ .Values.gonaomi.romsPath }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: roms-volume
          persistentVolumeClaim:
            claimName: {{ include "gonaomi.fullname" . }}-roms
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
