apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matterbridge-secret
  namespace: matterbridge
spec:
  encryptedData:
    HA_TOKEN: AgBizqm62CT5cFDYmJsH1YrEEkeNk6SMVf3K9iwBdNh9rhwDX+M/RLuq0QUFCixlFnLu9G4bwyoGPYfMGDyG+lOTPPzjTABCqOnSlKveCgMKV3GjrN2L+MosYvXR32B2VnuSgRmf4ymRtJP72Xsi5ORVqakGV+2D5C90WL82pvrLvWxTRLsJv3oIhzsW5/YdDF1v0eK7GgLl4Y6v/GwbJt82CVAi5WKZkDljLX0VT4G6TKKqW1uh3t4fJjDc781lWuEBwyciMCwr4kRAqmzqlq3Ek/k9+aH1fKzUtMFASkcOAWVDPoxm+NgMVLtiGMTgunxBiNwZinkkkMQDefXfjXhQofOe6iAqT1b4AbFHgMPJ7cDd3tYHFSC3rGaCNwz58mBfHyCmgiLiQvCCWmPtZ7IFnJ0CefTfWPU6ls4qzkD2XljO75LFQQIiWOxgy2/CUJfimg+a2Xrb51RfeDJG8AANJRqoHdpCm/UVv2S/LeiZ8r5/q/A3upwe7K2h67GQBHrwBbxTRn/6ECAzUb9c0f+2clLmE+wEoJe2w1VuPWtplsIGqMKCFga4tX8Qd55ZTvS1wFAFvi7QTyWVbXBe16svnwavx3cpI/U6db3zW/HMrirNvzzYr+TsQQyD4WP6MOVKRN4BUckXdQAU5OzvfXUwNIGJ4qDux7kymwtZIUopDFIjfSxt9HtbZeriTTDvwQqE2JiA0Cq2k0JeaGpF0l0lOnln5ZKSkqpJ0Gf57WOM/JaHVju5QsJtjyrfqhYBt8HIWKphk8VcUFAoNvta30bUus1XI6mx/XUtg3dRWIEzxwejsELtD7QjpDeifIikmFTOkX8qsgVgnsRP6RaJ1bSxwOxcUepuAKj4mWC4b1BC59vH0ZNUY1cCS/s9Tnla08ST9nPD7LXQ70x/LksOcr3phe9LA4mvk1wR7oI6mPRSQdnVaFpx/4s=
  template:
    metadata:
      name: matterbridge-secret
      namespace: matterbridge
