apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matterbridge-secret
  namespace: matterbridge
spec:
  encryptedData:
    HA_TOKEN: AgCWXiGgRVrPPHh3uYWBX7DagOnFSwgHvjl2ijOMx4hHTB0g3+673FIy9Own38ZO2Y6xhYZRGleV/KfSIzfuhz3cVWvYiyxFPEd+pEFNMrlFQAaOvRTvbDkbLDRr9IsiuCmwiKPK1K8YhbT61Z+Fwqy7MjFqIxw2g0RVaNfCc3qoiVuHUkI+xZ+TR7ygfJhIx+AEGqeqS4pjG79un4sRUAFieS2M7liwfbW2CZfnVM/fkyFCUbXnowU0/p8THm0T36kHggFMQEorwBMyeKcE3n2KImE6rdCzA7etqhxsxccE439VWWAzTizxb6SftlL05yPppuq+TWo4VjqSHuvU5AWFzSgHxfYtEYDm/VqbIZI9h3yo4HGT6d3exPilHm0zQ2y2HBs3C+gg9kmCFH9OH281TNYUZR9g1adc+lObOLIOIewV2JTk/6SHqNWPHv4oSdcB9kmpDvWsKgq+yPJW+Aum7jKeiLaifoMqL2fnMJhatp4oQ+hwjP20wDSHQIaIgb8dgdm1n8if9HjkPxip4/0RlYH7j8usJUixQIQbI8xYVuvdYg1ssFAtWmQn/8pqvSR3qA9R0WxUGfvG004uUIgv+p7xMyxRtxFm5NPsc5IGjpE5HQyXCvvn6A7hiIMfGzhvJhw62I7pW2s1cM1lYwSlWWt12f7pN4poVMAzgiC1+AP+SOsiBYw47bBT812xOKM8cuRVdVaaqJhHV2wCwdiqInnmTTC4XWLpc8x6u9IRLv+GCIQyoiJPVsZ7f7N3rmDZhfWgm7OpEm21PnjY92xyHaK5je++FWhhGL1AgOmg2obW+cBnPdAV0fJqvW2QVywQwxaClc5qB/zkzjl0omvz7uKbYu7WCHHfIRCFMOjOWusaJn47zGWqAusjMewM+TeKNrxMBJxVLlSvxdNfm1w+AmKMsEgyGqhpQMwZaMaQ63AQw/n4nrE=
  template:
    metadata:
      name: matterbridge-secret
      namespace: matterbridge
