image:
  repository: luligu/matterbridge
  tag: 3.7.3
  pullPolicy: IfNotPresent

pvc:
  data:
    size: 100Mi
    storageClass: openebs-hostpath

haWsUrl: wss://hass.home.fossar.net

matterbridge:
  port: 5540
  passcode: 20242025
  discriminator: 3840
  frontendPort: 8283
  mdnsInterface: enp1s0
