---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freenas-provisioner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freenas-provisioner.name" . }}
    helm.sh/chart: {{ include "freenas-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  protocol: {{ .Values.freenas.protocol | b64enc }}
  host: {{ .Values.freenas.host | b64enc }}
  port: {{ .Values.freenas.port | replace ":" "" | b64enc }}
  username: {{ .Values.freenas.username | b64enc }}
  password: {{ .Values.freenas.password | b64enc }}
  allowInsecure: {{ .Values.freenas.allowInsecure | b64enc }}
