---
- name: daemon-reload
  shell: systemctl daemon-reload

- name: restart tftpd-hpa
  service:
    name: tftpd-hpa
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted
