---

- block:
    - name: Ensuring firefox is not installed via apt
      package:
        name: "{{item}}"
        state: absent
      with_items:
        - firefox
        - firefox-esr

    - name: Downloading firefox
      get_url:
        url: "{{firefox.url}}"
        dest: "{{firefox.installdir}}/firefox-{{firefox_version}}.tar.bz2"
        mode: 0644
      register: firefox_archive

    - block:
        - name: Deleting existing firefox
          file:
            path: "{{firefox.installdir}}/firefox"
            state: absent

        - name: Installing firefox
          unarchive:
            src: "{{firefox.installdir}}/firefox-{{firefox_version}}.tar.bz2"
            remote_src: yes
            dest: "{{firefox.installdir}}"
      when: firefox_archive.changed

    - name: Linking to binaries
      file:
        src: "{{firefox.installdir}}/firefox/firefox"
        dest: /usr/local/bin/firefox
        state: link
  become: yes
  become_user: root
