---

- block:
    - name: Creating destination directory if needed
      file:
        state: directory
        path: "{{kubectl.installdir}}"

    - name: Downloading and installing kubectl
      get_url:
        url: "{{kubectl.url}}"
        dest: "{{kubectl.installdir}}/kubectl-{{kubectl_version}}"
        checksum: "{{kubectl.checksum}}"

    - name: Setting executable bit on binary
      file:
        path: "{{kubectl.installdir}}/kubectl-{{kubectl_version}}"
        mode: 0755
        owner: "{{me}}"
        group: "{{me}}"

    - name: Symlinking to this version
      file:
        state: link
        src: "{{kubectl.installdir}}/kubectl-{{kubectl_version}}"
        dest: "{{kubectl.installdir}}/kubectl"
        owner: "{{me}}"
        group: "{{me}}"

    - name: Symlinking to this version from /usr/local/bin
      file:
        state: link
        src: "{{kubectl.installdir}}/kubectl-{{kubectl_version}}"
        dest: "/usr/local/bin/kubectl"
        owner: root
        group: root

    - name: Installing stern binary command
      get_url:
        url: "{{ stern.url }}"
        dest: "{{ stern.installdir }}"
        checksum: "{{ stern.checksum }}"

    - name: Making stern executable
      file:
        path: "{{ stern.installdir }}/stern_linux_amd64"
        mode: 0755

    - name: Symlinking stern
      file:
        state: link
        src: "{{ stern.installdir }}/stern_linux_amd64"
        dest: "/usr/local/bin/stern"
        owner: root
        group: root

  become: yes
  become_user: root
