---

- name: Updating sudoers file
  lineinfile:
    path: /etc/sudoers
    regexp: '^.sudo  ALL=(ALL:ALL) ALL'
    line: '%sudo ALL=(ALL) NOPASSWD:ALL'
    state: present
  when: ansible_os_family != 'Darwin'

- block:
    - import_tasks: init.yml
      tags: init
      when: ansible_os_family != 'Darwin'
    - import_tasks: golang.yml
      tags: golang
      when: ansible_os_family != 'Darwin'
    - import_tasks: zsh.yml
      tags: zsh
    - import_tasks: fzf.yml
      tags: fzf
    - import_tasks: vim.yml
      tags: vim
    - import_tasks: xscreensaver.yml
      tags: xscreensaver
      when: ansible_os_family != 'Darwin'
    - import_tasks: xmonad.yml
      tags: xmonad
      when: ansible_os_family != 'Darwin'
    - import_tasks: rxvt-unicode.yml
      tags: rxvt
  become: yes
  become_user: "{{me}}"
