---

- name: Updating sudoers file
  lineinfile:
    path: /etc/sudoers
    regexp: '^.sudo  ALL=(ALL:ALL) ALL'
    line: '%sudo ALL=(ALL) NOPASSWD:ALL'
    state: present
  when: ansible_os_family != 'Darwin'

- block:
    - import_tasks: init.yml
      tags: init
      when: ansible_os_family != 'Darwin'
    - import_tasks: golang.yml
      tags: golang
      when: ansible_os_family != 'Darwin'
    - import_tasks: firefox.yml
      tags: firefox
      when: ansible_os_family != 'Darwin'
    - import_tasks: rxvt-unicode.yml
      tags: rxvt
    - import_tasks: zsh.yml
      tags: zsh
    - import_tasks: fzf.yml
      tags: fzf
    - import_tasks: vim.yml
      tags: vim
    - import_tasks: tig.yml
      tags: tig
    - import_tasks: xscreensaver.yml
      tags: xscreensaver
      when: ansible_os_family != 'Darwin'
    - import_tasks: xmonad.yml
      tags: xmonad
      when: ansible_os_family != 'Darwin'
    - import_tasks: terraform.yml
      tags: terraform
      when: ansible_os_family != 'Darwin'
    - import_tasks: onepassword.yml
      tags: onepassword
      when: ansible_os_family != 'Darwin'
    - import_tasks: kubectl.yml
      tags: kubectl
      when: ansible_os_family != 'Darwin'
    - import_tasks: vault.yml
      tags: vault
      when: ansible_os_family != 'Darwin'
    - import_tasks: helm.yml
      tags: helm
      when: ansible_os_family != 'Darwin'
  become: yes
  become_user: "{{me}}"
