---

- block:
    - name: Creating destination directory if needed
      file:
        state: directory
        path: "{{ onepassword.installdir }}"

    - name: Downloading 1password linux command line
      unarchive:
        src: "{{ onepassword.url }}"
        remote_src: yes
        dest: "/tmp"

    - name: Copying binary
      copy:
        remote_src: true
        src: "/tmp/op"
        dest: "{{ onepassword.installdir }}/op-{{ onepassword.version }}"
        owner: "{{ me }}"
        group: "{{ me }}"
        mode: 0755

    - name: Symlinking to this version
      file:
        state: link
        src: "{{ onepassword.installdir }}/op-{{ onepassword.version }}"
        dest: "{{ onepassword.installdir }}/op"
        owner: "{{me}}"
        group: "{{me}}"
  become: yes
  become_user: root
