---
# Compile manually urxvt because the one from Debian has a bug :
# it does not support wide glyphs used in powerline fonts
- name: Verifying urxvt installation
  stat:
    path: /usr/local/urxvt-installed
  register: urxvt_installed

- block:
    - name: Ensuring compile dir is not present
      file:
        path: /tmp/rxvt-unicode
        state: absent
      tags: urxvt_git

    - name: Ensuring rxvt packages are not installed
      become: yes
      become_user: root
      package:
        name: "{{item}}"
        state: absent
      with_items:
        - rxvt
        - rxvt-unicode
        - rxvt-unicode-256color

    - name: Installing required building packages
      become: yes
      become_user: root
      package:
        name: "{{item}}"
        state: present
      with_items:
        - build-essential
        - git
        - libperl-dev
        - libx11-dev

    # Original repo: cvs -z3 -d :pserver:anonymous@cvs.schmorp.de/schmorpforge co rxvt-unicode
    - name: Checking out urxvt source tree from git
      git:
        repo: https://github.com/yusiwen/rxvt-unicode
        dest: /tmp/rxvt-unicode
      tags: urxvt_git

    - name: Checking out urxvt dependencies
      git:
        repo: https://github.com/yusiwen/{{ item }}
        dest: /tmp/rxvt-unicode/{{ item }}
      with_items:
        - libev
        - libecb
        - libptytty
      tags: urxvt_git

    #- name: Copying installation script to remote
    #  copy:
    #    src: urxvt-widechars.patch
    #    dest: /tmp/rxvt-unicode

    #- name: Patching urxvt
    #  shell: patch -Np1 -i urxvt-widechars.patch
    #  args:
    #    chdir: /tmp/rxvt-unicode

    #- name: Installing urxvt unicode build dependencies
    #  become: yes
    #  become_user: root
    #  apt:
    #    state: build-dep
    #    pkg: rxvt-unicode-256color

    - name: Configuring urxvt
      shell: ./configure --prefix="/usr/local" --enable-everything --enable-256-color --enable-unicode3 --enable-xft --enable-transparency --enable-font-styles --enable-frills
      args:
        chdir: /tmp/rxvt-unicode

    - name: Compiling urxvt
      shell: make
      args:
        chdir: /tmp/rxvt-unicode

    - name: Installing urxvt
      become: yes
      become_user: root
      shell: make install
      args:
        chdir: /tmp/rxvt-unicode

    - name: Cleaning compile dir
      file:
        path: /tmp/rxvt-unicode
        state: absent

    - name: Creating witness file
      become: yes
      become_user: root
      file:
        path: /usr/local/urxvt-installed
        state: touch
  when: urxvt_installed.stat.exists is not defined or not urxvt_installed.stat.exists
