---

# Compile manually urxvt because the one from Debian has a bug :
# it does not support wide glyphs used in powerline fonts
- name: Verifying urxvt installation
  stat:
    path: /usr/local/urxvt-installed
  register: urxvt_installed

- block:
    - name: Ensuring compile dir is not present
      file:
        path: /tmp/rxvt-unicode
        state: absent

    - name: Ensuring rxvt packages are not installed
      become: yes
      become_user: root
      package:
        name: "{{item}}"
        state: absent
      with_items:
        - rxvt
        - rxvt-unicode
        - rxvt-unicode-256color
    
    - name: Installing required building packages
      become: yes
      become_user: root
      package:
        name: "{{item}}"
        state: installed
      with_items:
        - cvs
        - libperl-dev
        - libx11-dev
    
    - name: Checking out urxvt source tree
      shell: cvs -z3 -d :pserver:anonymous@cvs.schmorp.de/schmorpforge co rxvt-unicode
      args:
        chdir: /tmp
      tags: urxvt_cvs

    - name: Copying installation script to remote
      copy:
        src: urxvt-widechars.patch
        dest: /tmp/rxvt-unicode
    
    - name: Patching urxvt
      shell: patch -Np1 -i urxvt-widechars.patch
      args:
        chdir: /tmp/rxvt-unicode

    - name: Installing urxvt unicode build dependencies
      become: yes
      become_user: root
      apt:
        state: build-dep
        pkg: rxvt-unicode-256color

    - name: Configuring urxvt
      shell: ./configure --prefix="/usr/local" --enable-everything --enable-256-color --enable-unicode3 --enable-xft --enable-transparency --enable-font-styles --enable-frills
      args:
        chdir: /tmp/rxvt-unicode

    - name: Compiling urxvt
      shell: make
      args:
        chdir: /tmp/rxvt-unicode
    
    - name: Installing urxvt
      become: yes
      become_user: root
      shell: make install
      args:
        chdir: /tmp/rxvt-unicode

    - name: Cleaning compile dir
      file:
        path: /tmp/rxvt-unicode
        state: absent
    
    - name: Creating witness file
      become: yes
      become_user: root
      file:
        path: /usr/local/urxvt-installed
        state: touch
  when: urxvt_installed.stat.exists is not defined or not urxvt_installed.stat.exists

# Conf part
- name: Creating some directories
  file:
    state: directory
    mode: 0755
    path: "{{item}}"
  with_items:
    - "{{home}}/.urxvt"
    - "{{home}}/.urxvt/ext"
    - "{{home}}/.config"
    - "{{home}}/.config/fontconfig"
    - "{{home}}/.config/fontconfig/conf.d"
    - "{{home}}/.local"
    - "{{home}}/.local/share"
    - "{{home}}/.local/share/fonts"

- name: Installing urxvt-font-size
  get_url:
    url: "{{urxvt_font_size.url}}"
    dest: "{{home}}/.urxvt/ext/font-size"
    checksum: "{{urxvt_font_size.checksum}}"

- name: Installing powerline fonts
  git:
    repo: https://github.com/powerline/fonts
    dest: "{{home}}/.powerline-fonts"
    depth: 1
    update: yes

- name: Installing powerline fonts
  shell: ./install.sh && cp fontconfig/*.conf {{home}}/.config/fontconfig/conf.d && touch {{home}}/.powerline-fonts/installed
  args:
    chdir: "{{home}}/.powerline-fonts"
    creates: "{{home}}/.powerline-fonts/installed"

- name: Installing .Xresources file
  template:
    src: Xresources.j2
    dest: "{{home}}/.Xresources"
