---

- name: Installing xmonad and dependencies
  become: yes
  become_user: root
  package:
    name: "{{item}}"
    state: present
  with_items:
    - xmonad
    - dmenu
    - dzen2
    - conky-all
    - lm-sensors
    - stalonetray

- name: directories
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
  with_items:
    - "{{home}}/.xmonad"
    - "{{home}}/.xmonad/scripts"
    - "{{home}}/.xmonad/icons"

- name: files
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: 0555
  with_items:
    - src: icons/net_wired.xbm
      dest: "{{home}}/.xmonad/icons/net_wired.xbm"
    - src: icons/net_up_03.xbm
      dest: "{{home}}/.xmonad/icons/net_up_03.xbm"
    - src: icons/bat_full_02.xbm
      dest: "{{home}}/.xmonad/icons/bat_full_02.xbm"
    - src: icons/cpu.xbm
      dest: "{{home}}/.xmonad/icons/cpu.xbm"
    - src: icons/mem.xbm
      dest: "{{home}}/.xmonad/icons/mem.xbm"
    - src: icons/clock.xbm
      dest: "{{home}}/.xmonad/icons/clock.xbm"
    - src: icons/separator.xbm
      dest: "{{home}}/.xmonad/icons/separator.xbm"
    - src: brightness.sh
      dest: "{{home}}/.xmonad/scripts"
    - src: xmonad-kube-switch-ctx.sh
      dest: "{{home}}/.xmonad/scripts"
  tags: xmonad-config

- name: Installing easyopt script
  git:
    repo: 'https://github.com/nmaupu/easyopt.git'
    dest: "{{home}}/.xmonad/scripts/easyopt"
  tags: xmonad-config

- name: Installing conky configuration
  template:
    src: conky-dzen.j2
    dest: "{{home}}/.xmonad/scripts/conky-dzen"
    mode: 0444

- name: Installing xsession lightdm file
  become: yes
  become_user: root
  copy:
    src: xsession.desktop
    dest: /usr/share/xsessions
    mode: 0644
  notify:
    - restart lightdm

- name: Installing xsession file
  copy:
    src: xsession
    dest: "{{home}}/.xsession"
    mode: 0555
  notify:
    - restart lightdm

- name: Installing stalonetray config file
  template:
    src: stalonetrayrc.j2
    dest: "{{home}}/.stalonetrayrc"
    mode: 0444

- name: Configuring xmonad
  template:
    src: xmonad.hs.j2
    dest: .xmonad/xmonad.hs
  notify:
    - recompile xmonad
  tags: xmonad-config
