---

- name: Installing required packages
  become: yes
  become_user: root
  package:
    name: zsh
    state: latest
  when: ansible_os_family != 'Darwin'

- name: Installing required packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - zsh
    - coreutils
  when: ansible_os_family == 'Darwin'

- name: Getting dircolors
  get_url:
    url: "{{dircolors.url}}"
    dest: "{{home}}/.dircolors"
    checksum: "{{dircolors.checksum}}"

- name: Installing antigen
  get_url:
    url: "{{antigen.url}}"
    dest: "{{home}}/.antigen.zsh"
  notify:
    - antigen apply

- name: Creating .zshrc.d directory
  file:
    state: directory
    mode: 0755
    path: "{{home}}/.zshrc.d"

- name: Creating .zshrc.d files
  copy:
    src: "{{ item }}"
    dest: "{{ home }}/.zshrc.d"
    mode: 0644
  with_items:
    - zshrc.d/java
    - zshrc.d/k8s-and-misc

- name: Configuring p10k
  copy:
    src: p10k.zsh
    dest: "{{home}}/.p10k.zsh"

- name: Configuring zsh
  template:
    src: zshrc.j2
    dest: "{{home}}/.zshrc"
  notify:
    - antigen apply
