---

- name: Installing required packages
  become: yes
  become_user: root
  package:
    name: zsh
    state: latest
  when: ansible_os_family != 'Darwin'


- name: Installing required packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - zsh
    - coreutils
  when: ansible_os_family == 'Darwin'

- name: Getting dircolors
  get_url:
    url: "{{dircolors.url}}"
    dest: "{{home}}/.dircolors"
    checksum: "{{dircolors.checksum}}"

- name: Installing antigen
  get_url:
    url: "{{antigen.url}}"
    dest: "{{home}}/.antigen.zsh"
    checksum: "{{antigen.checksum}}"
  notify:
    - antigen apply

- name: Configuring zsh
  template:
    src: zshrc.j2
    dest: "{{home}}/.zshrc"
  notify:
    - antigen apply
