---

- name: Setting sysctl for golang ping library usage
  sysctl:
    name: net.ipv4.ping_group_range
    value: 0 2147483647
    state: present

- name: Downloading gotomation binary
  uri:
    url: https://github.com/nmaupu/gotomation/releases/download/{{ gotomation.version }}/gotomation-{{ gotomation.arch }}-{{ gotomation.version }}
    dest: /usr/local/bin/gotomation-{{ gotomation.arch }}-{{ gotomation.version }}
    mode: 0755
    status_code: 200
  notify:
    - restart gotomation

- name: Installing systemctl service file
  template:
    src: gotomation.service.j2
    dest: /etc/systemd/system/gotomation.service
    owner: root
    group: root
    mode: '0755'
  notify:
    - systemctl reload
    - restart gotomation

- name: Updating gotomation configuration
  template:
    src: gotomation.yaml.j2
    dest: "{{ gotomation.config }}"
    owner: "{{ gotomation.user }}"
    group: "{{ gotomation.group }}"
    mode: 0600

- name: Activating gotomation service
  service:
    name: gotomation
    state: started
    enabled: yes
