---

- name: Setting sysctl for golang ping library usage
  sysctl:
    name: net.ipv4.ping_group_range
    value: 0 2147483647
    state: present

- name: Downloading gotomation binary
  get_url:
    url: https://github.com/nmaupu/gotomation/releases/download/{{ gotomation.version }}/gotomation-{{ gotomation.arch }}-{{ gotomation.version }}
    dest: /usr/local/bin/gotomation-{{ gotomation.arch }}-{{ gotomation.version }}
    mode: 0755
  register: gotomation_binary
  notify:
    - restart gotomation

- name: Linking new binary
  file:
    state: link
    force: yes
    src: /usr/local/bin/gotomation-{{ gotomation.arch }}-{{ gotomation.version }}
    dest: /usr/local/bin/gotomation

- name: Cleaning old releases
  shell: |
    ls -1 /usr/local/bin/gotomation-* | grep -v "{{ gotomation.arch }}-{{ gotomation.version }}" | xargs rm -f


- name: Installing systemctl service file
  template:
    src: gotomation.service.j2
    dest: /etc/systemd/system/gotomation.service
    owner: root
    group: root
    mode: '0755'
  notify:
    - systemctl reload
    - restart gotomation

- name: Installing gotomation update conf script
  template:
    src: get-gotomation-config.sh.j2
    dest: /usr/local/bin/get-gotomation-config.sh
    owner: root
    group: root
    mode: '0755'

- name: Installing cron to auto udpate config
  cron:
    name: Getting gotomation config
    state: present
    job: /usr/local/bin/get-gotomation-config.sh
    user: "{{ gotomation.user }}"

- name: Activating gotomation service
  service:
    name: gotomation
    state: started
    enabled: yes
