---

certs:
  nfs:
    ip: 192.168.12.8
    path: /mnt/tank/le-certs

hass:
  defaults:
    user:
      username: "{{ lookup('vault', 'secret/hass', 'username') }}"
      password: "{{ lookup('vault', 'secret/hass', 'password') }}"
  secrets_yaml: |
    {{ lookup('vault', 'secret/hass', 'secrets.yaml') }}
