apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matterbridge-secret
  namespace: matterbridge
spec:
  encryptedData:
    HA_TOKEN: AgA08N7R6DXYOIU8nH25pifySnBhzq/A8ITRQp87IPks85AfTwTx0sOrHk8H+X3CJHDF9rBdN1sLxm+YbExy/t8Q7mXvr9DzeMVaexcyFpp3EPwx3Tio7K+fr4jItqmeQ+BVyO+tUvpTWlsdxenYcKVqz7ZaenW6wopx0KsIU4Ozer8kn5guDp8yg8nyc67AXRL5zwlhmTIRGfR9gqmPKN2Wk8WOALTjaCl0ELNgTX9S2trCW+rhHKXVbRUQiqCyrcb8oa/oEvms2EPu929oEeyrlfmE/I0zCxq1I/B+OU9PJ9Y01NA8sYdDg9kzia5uWHcZAabE68//MgYVX7pDgFgXg7bLOAYj9Hi4984IRKZVONRclPJCHyJJGanUTWyQG4woYiIuyDQOTzZ3+5CSwJW0hTuBV0s0lsz/M+Jx4pBDLbTr+ciGqQFlTaRiMzlpQ+6i+65fVDhfFYIaTrolzxZgKFCn/b5tQley8TcuvzypNeg3VNHGfMuIE8rKiTmIeFtMt5rEG6Vc3NKZitnz17La83qKJvW2AaClof05knI0F14aeh6I9E6WCQlAwfeJCNRg+XmRx1H/yY2ZDlgM2LVf/MOsIfZgRBOSBXk+/S/CyqnmeP8YcCm3G4WBMk8YILyxY3/KlsTG5LP2QdQvuuYSyerKgQrOwERGGdQPMtcjJ+ILPmpyohJGlAw0tL02j3BGqQzzv8KtK/jYxnJYNWKAJ/Zp4fsrXUTeXVywQXFjIlr92qhrmc4BJxDISnuZknB9qANadMGRJ6ocTDUVToqNZkUS1RqfXO7ppqEah4wHYwrOt71PAR1hvva7G2Zn4zAUmUsfPdtNDK4DvZ7/3q1rcMLguYBqztFQna04IvEZv7PV+dFJTJsst4W9Uip5y2yu5tf5/azyXrPiIAhAeAnMeajQ3lNEW92W4MhkmzrrzIfvPCNABog=
  template:
    metadata:
      name: matterbridge-secret
      namespace: matterbridge
