---
global:
  domain: argocd.knas.home.fossar.net

configs:
  cm:
    statusbadge.enabled: true
    timeout.reconciliation: 600s

server:
  certificate:
    enabled: true
    domain: argocd.knas.home.fossar.net
    issuer:
      kind: ClusterIssuer
      name: google-dns-issuer-prod
  ingress:
    enabled: true
    tls: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hostname: argocd.knas.home.fossar.net
