---
namespace: kube-system

deployment:
  replicasCount: 1
  image: docker.io/nmaupu/freenas-provisioner:1.1
  imagePullPolicy: IfNotPresent
  args:
    - --insecure

resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 50Mi

freenas:
  username: TBD
  password: TBD
  host: TBD
  port: 443
  parentDataset: kube-nfs
