
---
workload:
  main:
    replicas: 1

service:
  tcp:
    loadBalancerIP: 192.168.12.100
    externalTrafficPolicy: Cluster
    web:
      port: 80
      protocol: http
    websecure:
      port: 443
      protocol: https

metrics:
  main:
    enabled: false
