---

- name: restart firewall
  service:
    name: firewall
    state: restarted

- name: reload firewall
  service:
    name: firewall
    state: reloaded

- name: reload dhcp
  service:
    name: dnsmasq
    state: reloaded

- name: restart dhcp
  service:
    name: dnsmasq
    state: restarted
