---

# Parameters:
# kubde_nodes: array of all kube nodes
# rproxy_conf_dir: Path to nginx configuration dir

- name: Installing nginx
  package:
    name: nginx
    state: present

- name: Creating nginx configuration
  template:
    src: nginx.conf.j2
    dest: "{{rproxy_conf_dir}}/nginx.conf"
  notify:
    - restart nginx

- name: Creating htpasswd file for photoweb
  htpasswd:
    create: yes
    path: "{{rproxy_conf_dir}}/htpasswd.photoweb"
    name: "{{item.name}}"
    password: "{{item.password}}"
  with_items:
    - "{{photoweb_users}}"
  notify:
    - restart nginx

- name: nginx service
  service:
    name: nginx
    state: started
    enabled: yes
