nfs_server: nfs.home.fossar.net

deluge:
  image: linuxserver/deluge:91
  ingress_hostname: deluge.home.fossar.net
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi
  daemon_port: 58846
  port_beg: 6800
  port_end: 7000
  storageDir: /mnt/dls
  nfs:
    name: dls
    accessModes:
      - ReadWriteMany
    storageSize: 500Gi
    mountpoint: /mnt/tank/kube-nfs/dls
    configSubPath: deluge-config
