---
image:
  repository: ghcr.io/home-operations/prowlarr
  tag: 2.0.5.5160
  pullPolicy: IfNotPresent
exportarrImage:
  repository: ghcr.io/onedr0p/exportarr
  pullPolicy: IfNotPresent
  tag: v2.3.0

securityContext:
  container:
    readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 9696

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/tank/dls/configs/prowlarr
    targetSelector:
      main:
        main:
          mountPath: /config
      exportarr:
        exportarr:
          mountPath: /config

ingress:
  main:
    enabled: true
    hosts:
      - host: prowlarr.knas.home.fossar.net
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        certificateIssuer: google-dns-issuer-prod
        enabled: true
      traefik:
        allowCors: false
        enabled: true
        entrypoints:
          - websecure

global:
  traefik:
    fixedMiddlewares:
      - name: chain-basic
        namespace: ingress-controller

workload:
  main:
    primary: true
    type: Deployment
    podSpec:
      securityContext:
        fsGroup: 1001
      containers:
        main:
          primary: true
          probes:
            liveness:
              enabled: true
              type: http
              path: /ping
              port: 9696
            readiness:
              enabled: true
              type: http
              path: /ping
              port: 9696
            startup:
              enabled: true
              type: http
              path: /ping
              port: 9696
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
  exportarr:
    enabled: true
    type: Deployment
    podSpec:
      containers:
        exportarr:
          enabled: true
          primary: true
          probes:
            liveness:
              enabled: true
              type: http
              path: /metrics
              port: 9696
            readiness:
              enabled: true
              type: http
              path: /metrics
              port: 9696
            startup:
              enabled: true
              type: http
              path: /metrics
              port: 9696
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001

metrics:
  main:
    labels:
      release: kube-prometheus-stack
