---
deployment:
  replicas: 1

service:
  single: true
  annotations:
    metallb.io/loadBalancerIPs: 192.168.100.1
  spec:
    externalTrafficPolicy: Local

ports:
  web:
    exposedPort: 80
    expose:
      default: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    exposedPort: 443
    expose:
      default: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

metrics:
  prometheus: null
