---

- name: Install utilities
  gather_facts: no
  hosts: pxe
  become: yes
  roles:
    - linux-base
    - pxe
  tags: pxe

- name: Install DNS server
  gather_facts: no
  hosts: raspbastion
  become: yes
  roles:
    - dns
  tags: dns

- name: Install kubectl client
  gather_facts: no
  hosts: raspbastion
  become: yes
  roles:
    - kubectl
  tags: kubectl

- name: Provisioning kube-rproxy jail
  hosts: kube-rproxy
  vars:
    jail_name: kube-rproxy
    kube_nodes:
      - knode1.home.fossar.net
      - knode2.home.fossar.net
      - knode3.home.fossar.net
  gather_facts: no
  roles:
    - freenas-jail
  tags: freenas-jail
