---

## CoreOS related
- name: Bootstraping python on coreos machines
  gather_facts: no
  hosts: coreos
  become: no
  roles:
    - defunctzombie.coreos-bootstrap
    - coreos-post
  tags:
    - always

## Linux related
- name: Installing utilities
  gather_facts: yes
  hosts: linux
  become: yes
  roles:
    - linux-base
  tags:
    - linux
    - always
- name: Installing services
  gather_facts: no
  hosts: raspbastion
  become: yes
  roles:
    - { role: pxe, tags: ['pxe'] }
    - { role: dns, tags: ['dns'] }
    - { role: kubectl, tags: ['kubectl'] }
