---

- name: Install utilities
  hosts: pxe
  become: yes
  roles:
    - linux-base
    - pxe
  tags: pxe

- name: Install DNS server
  hosts: raspbastion
  become: yes
  roles:
    - dns
  tags: dns
