---

## Firewall setup
- name: Configuring openwrt firewall
  gather_facts: yes
  hosts: openwrt
  become: no
  roles:
    - { role: gekmihesg.openwrt, tags: ['always'] }
    - { role: openwrt_firewall, tags: ['firewall'] }

## CoreOS related
- name: Bootstraping python on coreos machines
  gather_facts: no
  hosts: coreos
  become: no
  roles:
    - defunctzombie.coreos-bootstrap
    - coreos-postinstall
  tags:
    - always

## Linux related
- name: Installing utilities
  gather_facts: yes
  hosts: linux
  become: yes
  roles:
    - linux-base
  tags:
    - linux

## Raspbastion
- name: Installing raspbastion stuff
  gather_facts: no
  hosts: raspbastion
  become: yes
  roles:
    - { role: kubectl, tags: ['kubectl'] }
    - { role: irssi, tags: ['irc'] }
    - { role: irssi-autodl, tags: ['irc-autodl'] }

## IoT Raspbian
- name: Installing IoT raspbian
  gather_facts: no
  hosts: iot-raspbian
  become: yes
  roles:
    - { role: homeassistant, tags: ['homeassistant'] }
