---

- name: Install utilities
  gather_facts: yes
  hosts: pxe
  become: yes
  roles:
    - linux-base
    - pxe
  tags: pxe

- name: Install DNS server
  gather_facts: no
  hosts: pxe
  become: yes
  roles:
    - dns
  tags: dns

- name: Install kubectl client
  gather_facts: no
  hosts: pxe
  become: yes
  roles:
    - kubectl
  tags: kubectl
