---

## Firewall setup
- name: Configuring openwrt firewall
  gather_facts: yes
  hosts: openwrt
  become: no
  roles:
    - { role: gekmihesg.openwrt, tags: ['always'] }
    - { role: openwrt_firewall, tags: ['firewall'] }

## CoreOS related
- name: Bootstraping python on coreos machines
  gather_facts: no
  hosts: coreos
  become: no
  roles:
    - defunctzombie.coreos-bootstrap
    - coreos-postinstall
  tags:
    - always

## Linux related
- name: Installing utilities
  gather_facts: yes
  hosts: linux
  become: yes
  roles:
    - linux-base
  tags:
    - linux

## Raspbastion
- name: Installing raspbastion stuff
  gather_facts: no
  hosts: raspbastion
  become: yes
  roles:
    - { role: kubectl, tags: ['kubectl'] }
    - { role: irssi, tags: ['irc'] }
    - { role: irssi-autodl, tags: ['irc-autodl'] }

## IoT Raspbian
- name: Installing IoT raspbian
  gather_facts: no
  hosts: iot-raspbian
  become: yes
  roles:
    - { role: homeassistant, tags: ['homeassistant'] }
    - { role: zigbee2mqtt,   tags: ['zigbee2mqtt'] }
    - { role: mosquitto,     tags: ['mosquitto'] }
    - { role: gotomation,    tags: ['gotomation'] }
  tasks:
    - name: disabling bluetooth (conflict with hardware serial) - needs reboot
      lineinfile:
        path: /boot/config.txt
        line: dtoverlay=pi3-disable-bt
    - name: disabling hciuart service
      service:
        name: hciuart
        state: stopped
        enabled: no
    - name: Generating openssh key pair
      openssh_keypair:
        path: /home/pi/.ssh/id_rsa
        force: no
        owner: pi
        group: pi
        comment: iot-raspbian
        state: present
        type: rsa
        size: 4096
      tags:
        - ssh
    - name: Changing owner/group of the public key
      file:
        path: /home/pi/.ssh/id_rsa.pub
        owner: pi
        group: pi
        mode: '0644'
      tags:
        - ssh
    - name: Getting ssh public key
      command: cat /home/pi/.ssh/id_rsa.pub
      register: public_key
      tags:
        - ssh
        - ssh-public
    - name: Displaying SSH public key
      debug:
        msg: "SSH public key = {{ public_key.stdout }}"
      tags:
        - ssh
        - ssh-public
