---

## CoreOS related
- name: Bootstraping python on coreos machines
  gather_facts: no
  hosts: coreos
  become: no
  roles:
    - defunctzombie.coreos-bootstrap
    - coreos-postinstall
  tags:
    - always

## Linux related
- name: Installing utilities
  gather_facts: yes
  hosts: linux
  become: yes
  roles:
    - linux-base
  tags:
    - linux
#    - always

## Raspbastion
- name: Installing raspbastion stuff
  gather_facts: no
  hosts: raspbastion
  become: yes
  roles:
    - { role: pxe, tags: ['pxe'] }
    - { role: dns, tags: ['dns'] }
    - { role: kubectl, tags: ['kubectl'] }
    - { role: irssi, tags: ['irc'] }
    - { role: irssi-autodl, tags: ['irc-autodl'] }
