---

- name: Bootstraping work machine
  become: yes
  become_user: root
  gather_facts: yes
  hosts: work
  roles:
    - { role: linux-base, tags: ['linux-base'], when: ansible_os_family != 'Darwin'}
    - { role: willshersystems.sshd, tags: ['sshd'], when: ansible_os_family != 'Darwin' }
    - { role: work, tags: ['work'] }
