firewall_packages: []

firewall_network_interfaces:
  lan:
    ipaddr: 192.168.1.1

firewall_wireless_key: 0123456789
firewall_wireless:
  - device:
      name: radio0
      config:
        channel: auto
        legacy_rates: 1
        country: FR
    iface:
      name: default_radio0
      config:
        device: radio0
        network: lan
        mode: ap
        ssid: openwrt-5g
        encryption: psk2
  - device:
      name: radio1
      config:
        channel: auto
        legacy_rates: 1
        country: FR
    iface:
      name: default_radio1
      config:
        device: radio1
        network: lan
        mode: ap
        ssid: openwrt-2g
        encryption: psk2

firewall_dhcp:
  wan:
    interface: wan
    ignore: 1
  lan:
    ignore: 1
    interface: lan
    start: 100
    limit: 150
    leasetime: 12h
    force: 1

# See https://openwrt.org/docs/guide-user/base-system/dhcp
# for more details and options
firewall_dnsmasq_config:
  options:
    add_local_domain: 1
    domainneeded: 1
    boguspriv: 1
    filterwin2k: 0
    localise_queries: 1
    rebind_protection: 1
    rebind_localhost: 1
    local: /lan/
    domain: lan
    expandhosts: 1
    nonegcache: 0
    authoritative: 1
    readethers: 1
    leasefile: /tmp/dhcp.leases
    resolvfile: /tmp/resolv.conf.auto
    nonwildcard: 1
    localservice: 1

firewall_dhcp_static_leases: []

firewall_dhcp_static_leases_extras:
  leasetime: 12h

firewall_dns_entries: {}
#firewall_dns_entries:
#  192.168.1.10:
#    - name1
#    - name2
#    - name3

firewall_ports: {}
#firewall_ports:
#  test:
#    target: DNAT
#    src: wan
#    dest: lan
#    proto: tcp
#    src_port: 9090
#    dest_port: 9090
#    name: test redirect 9090

firewall_prometheus:
  listen_address: ::1
  listen_port: 9100

firewall_fstab:
  global:
    anon_swap: 0
    anon_mount: 0
    auto_swap: 0
    auto_mount: 1
    delay_root: 5
    check_fs: 0

firewall_pxe:
  nginx_port: 8080
  usb_mount_dir: /mnt/extstorage
  syslinux:
    url: https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux/syslinux-6.03.tar.gz

firewall_usb:
  mounts:
    - enabled: 1
      device: /dev/sda1
      enable_fsck: 0
      fstype: ext4
      options: rw,sync,noatime
      target: "{{ firewall_pxe.usb_mount_dir }}"

firewall_nfs_mount: {}
#  name: openwrt
#  host: nas_ip
#  path: /remote/nfs/path
#  options: nolock,noatime,rw
#  network: lan
#  fstype: nfs
