---

autodl_url: https://github.com/autodl-community/autodl-irssi/releases/download/2.6.1/autodl-irssi-v2.6.1.zip

deluge_server_address: "{{lookup('vault', 'secret/deluge', 'daemon_server')}}"
deluge_server_port: "{{lookup('vault', 'secret/deluge', 'daemon_port')}}"
deluge_server_username: "{{lookup('vault', 'secret/deluge', 'daemon_username')}}"
deluge_server_password: "{{lookup('vault', 'secret/deluge', 'daemon_password')}}"

tl_rsskey: "{{lookup('vault', 'secret/deluge', 'tl_rsskey')}}"

autodl_filters:
  movies_hd:
    enabled: "true"
    max-downloads: 1
    max-downloads-per: day
    max-size: 10GB
    download-duplicates: "false"
    match-categories: "Movies :: Bluray, Movies::HDRip, Movies::BlurayRip"
    resolutions: 720p,1080p
  series_hd:
    enabled: "true"
    max-downloads: 2
    max-downloads-per: day
    max-size: 10GB
    download-duplicates: "false"
    match-categories: "TV :: Episodes HD"
    resolutions: 720p,1080p
  series:
    enabled: "true"
    max-downloads: 5
    max-downloads-per: day
    max-size: 2GB
    download-duplicates: "false"
    match-categories: "TV :: Episodes"
