---
zsh_histsize: 50000

urxvt_font_size:
  url: https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size

dircolors:
  url: https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark
  checksum: sha1:a69a89705554ca0c66a7848496f8db7a3d6e2278

antigen:
  url: http://git.io/antigen

golang:
  url: https://dl.google.com/go/go1.11.5.linux-amd64.tar.gz
  installdir: /usr/local

terraform_version: 0.12.0
terraform_arch: linux_amd64
terraform:
  url: https://releases.hashicorp.com/terraform/{{terraform_version}}/terraform_{{terraform_version}}_{{terraform_arch}}.zip
  installdir: /opt/bin

kubectl_version: 1.14.2
kubectl_arch: linux/amd64
kubectl:
  url: https://storage.googleapis.com/kubernetes-release/release/v{{kubectl_version}}/bin/{{kubectl_arch}}/kubectl
  installdir: /opt/bin
  checksum: sha1:94866b439197f56d6e9011af7e79fda100b8ccbc

minikube_arch: linux/amd64
minikube:
  url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  installdir: /opt/bin

vault_version: 0.10.3
vault_arch: linux/amd64
vault:
  url: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip
  installdir: /opt/bin

helm_version: 2.11.0
helm:
  url: https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz
  installdir: /opt/bin

stern_version: 1.10.0
stern:
  url: https://github.com/wercker/stern/releases/download/{{ stern_version }}/stern_linux_amd64
  installdir: /opt/bin
  checksum: sha1:e702e8d28572e415798b928b13009c8004d901ff

firefox_version: 66.0.3
firefox:
  version: "{{ firefox_version }}"
  url: https://download-installer.cdn.mozilla.net/pub/firefox/releases/{{ firefox_version }}/linux-x86_64/en-US/firefox-{{ firefox_version }}.tar.bz2
  installdir: /usr/local

tig_version: 2.3.3
tig:
  version: "{{ tig_version }}"
  url: https://github.com/jonas/tig/releases/download/tig-{{ tig_version }}/tig-{{ tig_version }}.tar.gz
  installdir: /usr/local

onepassword_version: 0.4.1
onepassword:
  version: "{{ onepassword_version }}"
  url: https://cache.agilebits.com/dist/1P/op/pkg/v{{ onepassword_version }}/op_linux_amd64_v{{ onepassword_version }}.zip
  installdir: /opt/bin
