---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.32.0
      helm:
        releaseName: vault
        valueFiles:
          - $values/k8s/argocd/nas/deploy/vault/vault/values.yaml
    - repoURL: https://github.com/nmaupu-org/auto-home.git
      targetRevision: master
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
