---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
  name: firewall
  namespace: argocd
spec:
  dnsNames:
    - fw.home.fossar.net
    - firewall.home.fossar.net
    - openwrt.home.fossar.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: google-dns-issuer-prod
  privateKey:
    rotationPolicy: Always
  secretName: fw-cert
