---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
  name: homeassistant
  namespace: argocd
spec:
  dnsNames:
    - hass.home.fossar.net
    - homeassistant.home.fossar.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: google-dns-issuer-prod
  privateKey:
    rotationPolicy: Always
  secretName: homeassistant-cert
