---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
  name: nas
  namespace: argocd
spec:
  dnsNames:
    - nas.home.fossar.net
    - truenas.home.fossar.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: google-dns-issuer-prod
  privateKey:
    rotationPolicy: Always
  secretName: nas-cert
