{
 "title": "Home dash",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Batteries",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(hass_sensor_battery_percent{friendly_name=~\"^ATC_.*\"})",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hass_sensor_temperature_celsius{friendly_name=~\"^ATC.* temp$\"}",
     "legendFormat": "{{ friendly_name }}"
    },
    {
     "expr": "hass_switch_state{friendly_name=~\".* heater.?$\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_temperature_celsius{friendly_name=~\"^ATC_.*temp$\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "expr": "hass_sensor_temperature_celsius{friendly_name=~\"^ATC_.*temp$\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hass_sensor_humidity_percent{friendly_name=~\"^ATC_.*\"}",
     "legendFormat": "{{ friendly_name }}"
    },
    {
     "expr": "hass_sensor_humidity_percent{entity=\"sensor.dehum_bedroom_am2301_humidity\"}",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "hass_switch_state{entity=\"switch.estrade_relay\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 17 },
   "targets": [
    {
     "expr": "hass_sensor_humidity_percent{friendly_name=~\"^ATC.*\"}",
     "legendFormat": "{{ friendly_name }}"
    },
    {
     "expr": "hass_sensor_humidity_percent{entity=\"sensor.estrade_am2301_humidity\"}",
     "legendFormat": "Estrade hum"
    }
   ]
  },
  {
   "title": "Discharge",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "hass_sensor_battery_percent{friendly_name=~\"^ATC_.*\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  }
 ]
}