---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: home-assistant
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    release: kube-prometheus-stack
    app: home-assistant
spec:
  staticConfigs:
    - targets: ['hass.home.fossar.net']
      labels:
        job: prometheus
  metricsPath: /api/prometheus
  scheme: HTTPS
  authorization:
    type: Bearer
    credentials:
      name: home-assistant-prometheus-token
      key: token

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-prometheus-token
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    token: AgCnJtz72xXzQw+/C1/4ysD7QHdlUU9909dZvmdDXm1kW3HK8iZlTezJo9JZIiqdAjq1FDro9WRHnOkSidD/ivCwhUjwkjyN4dECgo+Y30q3wcYM56rdhFiPPMNY3NIRvfSXs/QG4hvjMLgcYXDMzVReAtxBWlwSNDPh9nVsrsET8q6+a91YzwJrpdwfWmg2Hiq3UanQHBIZCrsyHI0EDpcDmeqiwlooDCD3+Tbb0mq5aPiOoAhMwlBfnzuGviFHwOqtz9t2Ooq4SzD0f3LV5qwRG814RQPqqjFzjswSzGdyVsJi9S9cAD5sLLs6uX/Rp8THA4I5sfFXsx+5EoHEpszZb2WWqmK4lKS7hp5dJQ3I2a07k00MacZFSTXBOhn3o19Mq5vU13aMAJPDozMER9e162FdMd3foiPVsgbmM0ha0EQdCj1wwfnQpewwaC2Sp/eZxRfdclxyBjAxwc4m6DJ9IxYJg1neFSBrJr6dgmnk+h1fV2sNK1s3ukLfJxjCbWeoYpO3VpZmgR6Oetin16OAvCqHHusd3eFdK+/7RbfjKnP9x7WUL/Vm0VFNwqUW2XthlkoBamLq+vbzUke4+lB6jeKhfyK0GCXUJQ4kusZVx8XT70ut+57rClmtzGuBOCVhdUrKNQVYz+cUFfAtdALd1MXyrfqxpvcaDeK3BGHH1XN//+PGiA07/VCfHtLuvAJA+pBUi0QpUAzCf0pEnR0Ra5d/0UqiY0r4+LHqIwiYIAtLpGz4HXP2jVoImbbBkpBx2sns12mJzS/VIcWJVjWGAzDvygjV/FNdQU0UlFFpIVBYrBA2Lc1c6Daqx/1xu5DCwQXSuRL/3DQ3dGTreY3yIB6I8EWW0tJyAtrhk8G9iXMIm9If56O1GanP1shjkGZYjYhk9ddBNMBJyEPHQrG5sYOy53kSpgdZqRxOGXx1KOekXQdKVZA=
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-prometheus-token
      namespace: monitoring
    type: Opaque
