{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "gladys.serviceAccountName" . }}
  labels:
{{ include "gladys.labels" . | indent 4 }}
{{- end -}}
