---
service:
  metrics:
    enabled: false
    ports:
      metrics:
        enabled: false

workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
  exportarr:
    podSpec:
      containers:
        exportarr:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/tank/dls/configs/sonarr
    targetSelector:
      main:
        main:
          mountPath: /config
      exportarr:
        exportarr:
          mountPath: /config
          readOnly: true
  online:
    enabled: true
    type: hostPath
    hostPath: /mnt/tank/dls
    mountPath: /mnt/dls

metrics:
  main:
    enabled: false

ingress:
  main:
    enabled: true
    hosts:
      - host: sonarr.knas.home.fossar.net
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        certificateIssuer: google-dns-issuer-prod
        enabled: true
      traefik:
        allowCors: false
        enabled: true
        entrypoints:
          - websecure

global:
  traefik:
    fixedMiddlewares:
      - name: chain-basic
        namespace: ingress-controller
