---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-ext4
parameters:
  recordsize: "128k"
  compression: "off"
  dedup: "off"
  fstype: "ext4"
  poolname: "tank/openebs-zfs"
provisioner: zfs.csi.openebs.io
