{
 "title": "Home confort",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "location", "label": "location", "query": "label_values(temperature, job)" }
  ]
 },
 "panels": [
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(humidity{job=\"$location\",metric=\"SENSOR\"})"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(temperature{job=\"$location\",metric=\"SENSOR\"})"
    }
   ]
  },
  {
   "title": "Temperature / Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "expr": "sum(temperature{job=\"$location\",metric=\"SENSOR\"})",
     "legendFormat": "Temperature"
    },
    {
     "expr": "sum(humidity{job=\"$location\",metric=\"SENSOR\"})",
     "legendFormat": "Humidity"
    },
    {
     "expr": "-8.78469475556+1.61139411*sum(temperature{job=\"$location\",metric=\"SENSOR\"})+2.33854883889*sum(humidity{job=\"$location\",metric=\"SENSOR\"})-0.14611605*sum(temperature{job=\"$location\",metric=\"SENSOR\"})*sum(humidity{job=\"$location\",metric=\"SENSOR\"})-0.012308094*sum(temperature{job=\"$location\",metric=\"SENSOR\"})*sum(temperature{job=\"$location\",metric=\"SENSOR\"})-0.0164248277778*sum(humidity{job=\"$location\",metric=\"SENSOR\"})*sum(humidity{job=\"$location\",metric=\"SENSOR\"})+0.002211732*sum(temperature{job=\"$location\",metric=\"SENSOR\"})*sum(temperature{job=\"$location\",metric=\"SENSOR\"})*sum(humidity{job=\"$location\",metric=\"SENSOR\"})+0.00072546*sum(temperature{job=\"$location\",metric=\"SENSOR\"})*sum(humidity{job=\"$location\",metric=\"SENSOR\"})*sum(humidity{job=\"$location\",metric=\"SENSOR\"})-0.000003582*sum(temperature{job=\"$location\",metric=\"SENSOR\"})*sum(temperature{job=\"$location\",metric=\"SENSOR\"})*sum(humidity{job=\"$location\",metric=\"SENSOR\"})*sum(humidity{job=\"$location\",metric=\"SENSOR\"})",
     "legendFormat": "Heat Index"
    }
   ]
  }
 ]
}